### ISSUE TITLE
Workerd fails to send webSocketAutoResponse for Durable Object Hibernate API in local development.

### ISSUE THREAD

**Issue by safaalai** [cloudflare/workerd#1009]
Which Cloudflare product(s) does this pertain to?
Pages, Durable Objects, Wrangler dev

What version(s) of the tool(s) are you using?
3.5.0 Wrangler

What version of Node are you using?
18.16.1

What operating system are you using?
Mac OS 13.2.1

Describe the Bug
Workerd fails to send webSocketAutoResponse for Durable Object Hibernate API in local development.

Definitions
normal message = message processed by webSocketMessage handler which sends back an ack.
ping message = message processed by webSocketAutoResponse handler which sends back a pong

I start a pages project for local development using `npx wrangler pages dev -- npm start`.  npm start kicks off my dev server which is proxied by wrangler.  This project uses a pages function and a durable object to setup a webSocket connection using the Durable Object Hibernate API.  The project uses webSocketAutoResponse to setup a 'pong' response for every 'ping' request.

I get the following results when I try to send messages from the client to the server:

1. Single normal message ==> goes through and gets a response from the DO
2. Normal messages on intervals ==> every message gets a response from the DO
3. 'ping' auto messages on an interval by themselves ==> get no response
4. single normal message followed by 'pings' on intervals ==> normal message gets response, 1st ping gets response, subsequent pings get no response
5. normal & ping messages on intervals ==> normal & ping messages get a single response, all subsequent normal & ping messages get no response

Looking at the DO logs, any time auto messages are involved, (i.e. 'ping' message cases #3, #4, #5 above), I get:
```workerd/jsg/util.c++:275:` error: e = kj/compat/http.c++:3421: failed: expected !currentlySending; another message send is already in progress stack: 10b9e595f 10b9e3338 10b9f7ccd 10b9f07fe 10b9fb371 10b9f7ccd 10b9f07fe 10b9fb371 10b9f7ccd 10b9f07fe 10b9fb371 10b0ce270; sentryErrorContext = jsgInternalError Client error Error: internal error { stack: Error: internal error, message: internal error }```

**Comment by safaalai** [comment]
Note, I was asked by @milan_cf on Discord to open the bug under workerd.

**Comment by kentonv** [comment]
cc @MellowYarker (aka milan_cf on Discord)

**Comment by MellowYarker** [comment]
@jqmmes is looking into this, we think we know the issue but need to get a repro. He's out for the week so I may pick up when I have a chance.

**Comment by safaalai** [comment]
Thanks for looking into this.  I'm working on creating a repo with code that produces the bug.  Will post here tomorrow.

**Comment by safaalai** [comment]
Here's a repo that reproduces the bug.  Instructions are in the readme file.

https://github.com/safaalai/stencil-latest

**Comment by safaalai** [comment]
@MellowYarker & @jgmmes, any thoughts on when this bug may be looked into?

**Comment by MellowYarker** [comment]
@safaalai we've identified a problem and have been working on a fix, sorry for not updating here. We found a race condition that broke a requirement of our library's websocket implementation; fix looked easy enough at a glance, but has turned out to be somewhat complicated. I expect the update will be in next weeks release, not exactly sure when wrangler updates its Workerd version but @jqmmes will comment here when it's ready :slightly_smiling_face: 

Thanks for your patience!

**Comment by safaalai** [comment]
@MellowYarker any more news on this?

**Comment by jqmmes** [comment]
A PR that fixes this issue was merged, but it's still waiting to release in wrangler.

**Comment by safaalai** [comment]
Just checking in.  Any ideas when this may be released in Wrangler?

**Comment by jqmmes** [comment]
@safaalai this fix was briefly reverted, but it's going to be merged once again soon. I don't have an ETA for the wrangler release yet, but I think it won't take long.
