### ISSUE TITLE
[FEATURE] - Ability to setup TCP Socket timeout in workers

### ISSUE THREAD

**Issue by ghost** [cloudflare/workerd#1018]
It's not clear what the default TCP socket timeout is nor it's possible to specify one https://github.com/cloudflare/workerd/blob/main/src/cloudflare/internal/sockets.d.ts#L24

Would be awesome to have socketTimeout in the SocketOptions object.

If you point me to how to update documentation for default tcp timeout or point me how to add this I can send a PR

**Comment by kentonv** [comment]
Hi @dm161,

This is a good idea, but would require a bit more than just a PR in workerd. On Cloudflare, TCP connections go through at outbound proxy which would need to be responsible for setting the timeout. We also need to decide things like what should happen if the connection is answered by another Worker (once Workers gain the ability to accept connections) and thus never actually crosses TCP -- is the timeout ignored or is it emulated? Somewhat related, do we want to express timeouts as literally just a time duration or do we want to provide control over the various low-level TCP keepalive knobs? (I would vote for just an interval, but not sure how complicated it may be to map to the low-level options.)

cc'ing @irvinebroque to think about where this fits on the roadmap.

**Comment by dom96** [comment]
I'm curious if something as simple as a `setTimeout` + closure of the Socket when the timeout triggers would work for your use case.

One challenge is that you cannot currently detect when the socket connection is established (as we lack an `opened` promise in the `Socket` instance), but maybe for your use case the server always sends some data at the start of the connection anyway, which would let you use that as the point when the connection is established and the timeout can be cancelled. If an `opened` promise is all that is needed then that might be implementable in just workerd.

**Comment by jasnell** [comment]
There are really two timeouts needed, I would think: (a) a time limit for establishing the connection and (b) an idle timeout that closes the connection if it remains idle for too long.

For (a) something as simple as an `AbortSignal` passed into the `connect()` call could be sufficient:

```js
// If the connection is not established within 10 seconds, abort the attempt
const s = connect('...', { signal: AbortSignal.timeout(10_000) });
```

The idle timeout is more difficult, and as @kentonv suggests requires deeper work in both workerd and the internal infrastructure.

**Comment by dom96** [comment]
True, we can match `fetch` here. Though there are other use cases out there for the `opened` promise than just timeouts (and the websocket API as it stands right now supports it too) so it may be worth implementing in any case. 

@dm161 if you want to give writing a PR a go: following how the `closed` promise is implemented (in sockets.c++) is a good route to take. You likely want to resolve the new `opened` promise you introduce inside the `handleProxyStatus` method.

> The idle timeout case (b) is more difficult, and as @kentonv suggests requires deeper work in both workerd and the internal infrastructure.

Why is that? Similarly to (a) wouldn't a naive approach of closing the socket when no data is received work well for most use cases?

**Comment by jasnell** [comment]
> Why is that? Similarly to (a) wouldn't a naive approach of closing the socket when no data is received work well for most use cases?

I suppose it could. Every bit of data transmitted or received could reset a timer.

**Comment by lyc8503** [comment]
> An opened promise would exactly be the right and optimal compromise for this. Can I help in any way on the codebase? My cpp is rusty but don’t think will be too difficult if it’s just a matter of bubbling it up to the ts code

One more vote for an `opened` promise, which could helps developers get more control of the timing and connection status.

**Comment by dom96** [comment]
`opened` is now implemented
