### ISSUE TITLE
Bun Runtime Support for Cloudflare Pages

### ISSUE THREAD

**Issue by SaucyOfficiale** [cloudflare/workerd#1160]
Please support Bun runtime for Cloudflare Pages. I can't use it with Cloudflare Pages and given its popularity lately compared to Node, this is a must for Cloudflare. Thank you.

**Comment by garretcharp** [comment]
Fwiw cloudflare doesnt support the Node runtime, and I doubt the bun runtime would be supported either.

**Comment by kentonv** [comment]
Are you asking for this to be supported an build time (for building your page's static assets), or at runtime (to run Worker code / Pages Functions serving live requests)?

**Comment by SaucyOfficiale** [comment]
=

> Are you asking for this to be supported an build time (for building your page's static assets), or at runtime (to run Worker code / Pages Functions serving live requests)?

Both. Runtime and Build Time. 

For runtime, Cloudflare uses the V8 engine. Bun has Javascript Core which is just faster. I don't know how to switch the runtime to Bun with Cloudflare Pages, there is no way.

For build time, I was hoping Bun could be listed on : 
https://developers.cloudflare.com/pages/platform/language-support-and-tools/

Where Go, Node, Python, and Ruby are listed.

**Comment by kentonv** [comment]
Cloudflare's runtime is `workerd` -- that's the repo you're posting this issue on. We've built our runtime for the specific needs of our edge compute environment. No other runtime is designed in the way we need. Sorry, but there's no chance we'd adopt a third-party runtime for our environment.

Pages' build environment is a different matter. However, this isn't the right issue tracker for Pages. You could post your request on the Pages community here: https://community.cloudflare.com/c/developers/cloudflare-pages/69

> Bun has Javascript Core which is just faster.

This is actually hotly debated. That said, it's possible that `workerd` could support alternate JavaScript engines someday. Most of `workerd`'s code is not specific to V8; we could in principle swap out the JS engine for something else. This is not a priority at present, though.

**Comment by jasnell** [comment]
Going to go ahead and close this. As Kenton suggests, Pages' build environment is a completely different thing and is not relevant to this repo. Any discussion of Pages support for bun should be moved to that forum. As for workerd, it's not just a matter of "supporting bun". I could imagine a hypothetical future where we built on JavaScriptCore instead of v8, and it is theoretically possible, but it would be a significant long term effort given how deeply entrenched our use of v8 currently is. Not saying no but also can't say that it's at all a priority for us any time soon.

**Comment by SaucyOfficiale** [comment]
Hi someone from CF Team just told me here that the Cloudflare Discord (which I'm banned on under username SaucyOfficial idk why) has a Bun form for beta testing I don't have access to : 
https://community.cloudflare.com/t/no-bun-support-how/554291/5

Please enable Bun testing for the Cloudflare account under email saucysaturday@gmail.com thanks!



> Cloudflare's runtime is `workerd` -- that's the repo you're posting this issue on. We've built our runtime for the specific needs of our edge compute environment. No other runtime is designed in the way we need. Sorry, but there's no chance we'd adopt a third-party runtime for our environment.
> 
> Pages' build environment is a different matter. However, this isn't the right issue tracker for Pages. You could post your request on the Pages community here: https://community.cloudflare.com/c/developers/cloudflare-pages/69
> 
> > Bun has Javascript Core which is just faster.
> 
> This is actually hotly debated. That said, it's possible that `workerd` could support alternate JavaScript engines someday. Most of `workerd`'s code is not specific to V8; we could in principle swap out the JS engine for something else. This is not a priority at present, though.

**Comment by kentonv** [comment]
Walshy was talking about Bun support _at build time_ for Cloudflare Pages. Runtime will always be `workerd`.
