### ISSUE TITLE
🐛 Bug Report — Runtime APIs: WebSocket.close() logs `Request failed due to internal error` in Miniflare

### ISSUE THREAD

**Issue by jevakallio** [cloudflare/workerd#1299]
When calling `socket.close()` for a WebSocket connection inside a Durable Object logs the following error to Miniflare console.

```
workerd/util/symbolizer.c++:98: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.
workerd/server/server.c++:2525: error: Uncaught exception: kj/async.c++:212: disconnected: worker_do_not_log; Request failed due to internal error
stack: 1053b3473 10642ee4b 1064353eb 10642c3bf 10465cd27 104660313 10466014f 104660137 1064956f3 106495a3b 10649419b 106493f6b 1046541af 1a4743f27 106426c90 1053d7cf4 104e32574 104c16b00 104c16f0f 104af12e8 10469eabc 10539bc80 10539f060
```

For instance:

```ts
async webSocketMessage(ws, msg) {
  if (msg === "close me") {
    ws.close();
  }
}
```

Outputs:

<img width="1382" alt="image" src="https://github.com/cloudflare/workerd/assets/1203949/f2daad9f-d9ef-443f-9980-de82c7dffc8f">

The socket closes correctly. We are only seeing this error in Miniflare, not in Workers platform logs, but I'm not sure if that means the error is not occurring, or if it's just not being send to `wrangler tail`.

**Comment by MellowYarker** [comment]
I've opened a ticket to track internally, we won't be able to prioritize this for a bit. I'll update when someone can take a look.
