### ISSUE TITLE
🐛 Bug Report — Runtime APIs: Node Crypto X509Certificate Support

### ISSUE THREAD

**Issue by robertlong** [cloudflare/workerd#1304]
I'm currently using Cloudflare Workers with the [Apple App Store Server API](https://developer.apple.com/documentation/appstoreserverapi). This api uses JWS with X509 verification. In order to parse and verify responses from the server we need to be able to use the nodejs X509Certificate class.

Here's an example of it in use in the app-store-server-api nodejs library: https://github.com/agisboye/app-store-server-api/blob/main/src/Decoding.ts#L79

**Comment by fhanau** [comment]
This was implemented in https://github.com/cloudflare/workerd/pull/2335 and should work now. Feel free to reopen if you encounter any issues.

**Comment by imWildCat** [comment]
sorry, we're still using this error on latest runtime node-compact

Is `import ... from 'crypto'`  support or it must be prefixed with `node:`?




```ts
import { NextRequest, NextResponse } from 'next/server';
import { 
  decodeNotificationPayload, 
  isDecodedNotificationDataPayload, 
  isDecodedNotificationSummaryPayload 
} from 'app-store-server-api';
import { appStoreNotifications } from '@/db/schema';
import { drizzleOnWorkers } from '@/db/drizzle_from_env';
import crypto from 'node:crypto';

const APP_BUNDLE_ID = process.env.APP_BUNDLE_ID!;

export const runtime = 'edge';

export async function POST(request: NextRequest) {
  try {
    const { signedPayload } = await request.json() as { signedPayload: string };
    console.log("🚀 ~ POST ~ signedPayload:", signedPayload, 'crypto:', crypto, crypto.X509Certificate) // the last element is undefined.


    
    // Decode and verify the notification payload
    const payload = await decodeNotificationPayload(signedPayload); // error here
    console.log("🚀 ~ POST ~ payload:", payload)

```
