### ISSUE TITLE
Do not redeclare TS lib

### ISSUE THREAD

**Issue by dr-vortex** [cloudflare/workerd#1384]
After diving into worker-types with #1383, I realized that many of the `workers-types` are just modified from TS lib. Is there a reason for this? Why not `extend` pre-existing classes where needed?

For example, instead of re-declaring `Body`:

`worker-types` currently:
```ts
export declare abstract class Body {
  readonly body: ReadableStream | null;
  readonly bodyUsed: boolean;
  arrayBuffer(): Promise<ArrayBuffer>;
  text(): Promise<string>;
  json<T>(): Promise<T>;
  formData(): Promise<FormData>;
  blob(): Promise<Blob>;
}
```

`lib.dom.d.ts` (comments removed):
```ts
interface Body {
    readonly body: ReadableStream<Uint8Array> | null;
    readonly bodyUsed: boolean;
    arrayBuffer(): Promise<ArrayBuffer>;
    blob(): Promise<Blob>;
    formData(): Promise<FormData>;
    json(): Promise<any>;
    text(): Promise<string>;
}
```

Updated:
`worker-types/alias.d.ts`
```ts
export { Body };
```

`worker-types/index.d.ts`
```ts
import type { Body as FetchBody } from './alias';

export declare abstract class Body extends FetchBody {
  json<T>(): Promise<T>;
}
```

This would add a ton of reusability and compatibility to the types since the only code is changes from built-in classes. The following classes can use this approach:
- DOMException
- WorkerGlobalScope
- WorkerGlobalScopeEventMap
- Console
- console
- BufferSource
- WebAssembly
- ServiceWorkerGlobalScope
- addEventListener
- removeEventListener
- dispatchEvent
- btoa
- atob
- setTimeout
- clearTimeout
- setInterval
- queueMicrotask
- structuredClone
- fetch
- ...

I won't bother to list the 250+ symbols which only redeclare ones already present in TS lib, with little to no change.

**Comment by penalosa** [comment]
This is intentional. The types for `@cloudflare/workers-types` are generated directly from the workers runtime implementation, and so accurately match runtime behaviour. In most cases we're pretty close to spec-compliant with web standards, and so are similar to `lib.dom.d.ts`, but we recommend using `@cloudflare/workers-types` exclusively, and not typing your codebase against `lib.dom.d.ts`.
