### ISSUE TITLE
🐛 Bug Report — Runtime APIs: `alarm-scheduler` fails for inscrutable reason

### ISSUE THREAD

**Issue by huw** [cloudflare/workerd#1386]
Sometimes when I schedule alarms in a Durable Object, I get the following error:

```
workerd/server/alarm-scheduler.c++:203: warning: exception = kj/filesystem.c++:304: failed: expected strlen(part.begin()) == part.size() [6 == 71]; NUL character in path component; part = ��zUdc5238b9�$�v$7559429.sqlite
```

I tried looking through the source code, but it’s very hard to determine why this is occurring, ~~especially because I don’t think KJ is open source~~. The behaviour appears inconsistently (restarting usually fixes it), but if it helps the kinds of calls I’m making are:

- Schedule around 500ms in the future
- Schedule at the current date (via `Temporal.Now.instant()`, which uses `Date.now()` under the hood)

For both, I sometimes check for the presence of an existing alarm first, but not always. Any hints?

**Comment by dom96** [comment]
> especially because I don’t think KJ is open source

it is open source, it's in the capnp repo: https://github.com/capnproto/capnproto/tree/v2/c%2B%2B/src/kj

**Comment by huw** [comment]
Thanks for that—sorry! I tried looking a bit further but knowing the KJ code didn’t enlighten me much—it is hard to find where `workerd`/`wrangler` is calling that deep into the stack without a useful stack trace, which I’m not getting (mine just spits out an `LLVM_SYMBOLIZER` error a la cloudflare/workers-sdk#3631). I would love to debug this myself but it’s just too hard. Should I move this to `workers-sdk`?

**Comment by kentonv** [comment]
It's unlikely an issue in KJ. It looks like workerd is probably calling the filesystem APIs and passing a Path object that has already been freed.

**Comment by gregory** [comment]
> Thanks for that—sorry! I tried looking a bit further but knowing the KJ code didn’t enlighten me much—it is hard to find where `workerd`/`wrangler` is calling that deep into the stack without a useful stack trace, which I’m not getting (mine just spits out an `LLVM_SYMBOLIZER` error a la [cloudflare/workers-sdk#3631](https://github.com/cloudflare/workers-sdk/issues/3631)). I would love to debug this myself but it’s just too hard. Should I move this to `workers-sdk`?

Having the same issue, really hard to debug. 
I'm going through the same usage pattern, scheduling alarms at Date.now() or in a very near future.

**Comment by bkniffler** [comment]
Can confirm the bug appears if `setAlert(Date.now())`, but does not if `setAlert(Date.now()+1000)`

**Comment by JacobDanton** [comment]
I get this after setting the 3rd alarm regardless of how far in the future

**Comment by huw** [comment]
I’ve tried the following MWE, but I can’t reliably reproduce the bug on Wrangler `3.16.0` or `^3.17.0`:

```ts
export class Test implements DurableObject {
  constructor(private readonly state: DurableObjectState) {}

  async fetch() {
    await this.state.storage.setAlarm(Date.now() - 1000);
    return new Response("OK");
  };

  async alarm() {
    console.log("Alarm execution succeeded");
  }
}

const index: ExportedHandler<{ TEST: DurableObjectNamespace }> = {
	fetch: async (_, { TEST }) => await TEST.get(TEST.idFromName("test")).fetch("https://do")
};

export default index;
```

I also tried subtracting time from `Date.now()`, and trying to schedule multiple alarms at once. For now, I’m waiting to catch it again in Wrangler `^3.17.0`, which includes the stack trace symbolizer fixes and might (?) have a better stack trace. But any tips from the core team on how I can see a proper stack trace from KJ & workerd would be hugely appreciated :)

**Comment by jasnell** [comment]
I just looked quickly at alarm-scheduler.c++ and there's currently only one place we're passing along a `kj::PathPtr` that could potentially be a problem here. I just opened https://github.com/cloudflare/workerd/pull/1442 that ensures the `kj::Path` is attached and kept alive. I haven't repro'd the actual segfault locally yet so it would be helpful if someone who has repro'd it could give the potential fix in #1442 a try.

**Comment by jasnell** [comment]
For those of you who are reliably seeing this, can I ask someone to put together a simple repro worker that always fails for you. I'm unable to reproduce the issue on main

**Comment by jasnell** [comment]
Ok, think I've identified the issue and the fix (#1474)

**Comment by jasnell** [comment]
I've landed #1474 which should fix this issue (which is why the issue autoclosed). If you still see this issue once the workerd package is updated, let us know here and we can open this issue and keep investigating further.

**Comment by johnspurlock** [comment]
By any chance, did this change land in Workers prod around Wednesday of this week?  I saw a few alarms start re-firing around (all around `2023-12-13T20:30:00Z`) in 3 colos that I hadn't noticed weren't firing for months (!)

**Comment by kentonv** [comment]
@johnspurlock James' change is a fix to code that only runs in local testing; our production implementation of alarms is very different. Separately, though, I think I did hear someone say something about fixing a bug which had caused some alarms to fail to run, and that old alarms might start running as a result. I don't personally know the details of this. Maybe ask in the Durable Objects room on Discord?

**Comment by johnspurlock** [comment]
> @johnspurlock James' change is a fix to code that only runs in local testing; our production implementation of alarms is very different. Separately, though, I think I did hear someone say something about fixing a bug which had caused some alarms to fail to run, and that old alarms might start running as a result. I don't personally know the details of this. Maybe ask in the Durable Objects room on Discord?

Ah ok thanks, got a [response](https://discord.com/channels/595317990191398933/773219443911819284/1185599585498972231) a few days ago there:

> A bug with Durable Objects Alarms was fixed and will cause skipped alarms to run. Accounts with affected alarms will receive an email next week with more details
