### ISSUE TITLE
Vectorize `Matches` types don’t match returned values with `vectorize_query_metadata_optional`

### ISSUE THREAD

**Issue by huw** [cloudflare/workerd#1435]
I’ve bumped my compatibility date to `2023-11-23` and I’m calling:

```ts
VECTORIZE.query([1, 1, 1], { returnValues: true, returnMetadata: true })`
```

According to the types and [the docs](https://developers.cloudflare.com/workers/configuration/compatibility-dates/#vectorize-query-with-metadata-optionally-returned), I should get a flattened `vector` object:

https://github.com/cloudflare/workerd/blob/754bc0267643c8a00f7a29e5092cd22de1b82140/types/defines/vectorize.d.ts#L66-L84

Instead, I get:

```json
{"vectorId":"example_vector_id","score":0.5,"vector":{"id":"example_vector_id","values":[1,1, 2],"metadata":{}}}
```

(Permutations of the `returnValues` and `returnMetadata` structure return similar things; and if both are false the `vector` field is omitted entirely). FWIW this is against a worker that I’ve deployed to Cloudflare, not on the edge preview.

I am struggling to work out if this is an issue with the spec or the implementation, so I didn’t raise a PR. What’s going on? (cc @ndisidore since you seem to be on the git blames for this)

**Comment by andyjessop** [comment]
I am also getting the old format, using wrangler 3.0.0 and this command to create the index:

```
npx wrangler vectorize create notes-ai-index-2 --dimensions=1536 --metric=cosine
```

Incidentally, I also get a TS error on using the `filter` property in the `query` method:

```ts
const metadataMatches = await env.VECTORIZE_INDEX.query(vector, {
          topK: 20,
          // @ts-ignore
          filter: {
            filename,
          },
          returnMetadata: true,
        });
```

**Comment by huw** [comment]
Both are expected, neither the PR above that fixed this or the one that adds the filtering types have landed in Wrangler yet. They’ll land sometime over the next couple of weeks! Filters work in the meantime, but they’re just not typed yet.

**Comment by andyjessop** [comment]
In that case I highly recommend reverting the updates to the docs. It's quite misleading and has lost me a few hours today:

E.g.:
https://developers.cloudflare.com/vectorize/learning/metadata-filtering/

**Comment by huw** [comment]
Not my place to defend Cloudflare online, but the code in the docs works, it just won’t validate in TypeScript.

**Comment by andyjessop** [comment]
Just FYI, it looks like the `matches` object was updated yesterday (it broke my app unexpectedly), and the docs no longer match the code. I suppose this is all just because it's in beta, but it would be nice to be able to be notified when there are updates.

Docs: https://developers.cloudflare.com/vectorize/learning/query-vectors/

```json
{"score":0.999909486,"vectorId":"5","vector":{"id":"5","values":[58.79999923706055,6.699999809265137,3.4000000953674316],"metadata":{"url":"/products/sku/55519183"}}}
``` 

Actual as of today:

```json
{"id":"id","metadata":{"url":"/products/sku/55519183"},"score":0.999909486}
```

**Comment by huw** [comment]
Yeah, I agree with you on that. This is a very unusual change because instead of actually being behind a compatibility flag, it happened because the parsing of a compatibility flag broke. I guess they don’t have a process for safely changeboarding that?

**Comment by ndisidore** [comment]
Correct. We're sorry about the breaking change: ordinarily we gate these
behind compatibility flags but as @huw alludes to, there was an issue with
the compatibility flag logic itself that was not fixable in a globally
consistent way.
This is fixed now, so going forward for Vectorize, date gates should work
properly and there will be announcements and ample time given before any
kind of major change/depreciation.
