### ISSUE TITLE
Docker error: CODE_MOVED for unknown code block?

### ISSUE THREAD

**Issue by adronitis** [cloudflare/workerd#1472]
Running `wrangler dev --port=8000` inside Docker with:

```
/* eslint-disable */
import { Router } from 'itty-router'

const router = Router()
const routes =  JSON.parse(ROUTES)
const proxyTo = hostname => async request => {

  const url = new URL(request.url);
  const forwardedHost = url.hostname;
  url.hostname = hostname;

  const req = new Request(url, request);
  req.headers.append('X-Forwarded-Host', forwardedHost);

  return fetch(req);
}

routes.forEach(route => {
  router.all(route, proxyTo(FRONTEND_HOST));
});

router.all('/api/*', proxyTo(BACKEND_HOST))
router.all('/*', proxyTo(BACKEND_HOST))

addEventListener('fetch', (e) => {
  e.respondWith(router.handle(e.request))
})
```

Everything works fine if I run this outside of Docker, but if I put everything in Docker, when I want to do the proxy, I get:
```
worker-router-worker-1  | ✘ [ERROR] workerd/jsg/setup.c++:481: error: CODE_MOVED for unknown code block?
worker-router-worker-1  |
worker-router-worker-1  |   workerd/jsg/setup.c++:481: error: CODE_MOVED for unknown code block?
worker-router-worker-1  |   workerd/jsg/setup.c++:481: error: CODE_MOVED for unknown code block?
worker-router-worker-1  |   workerd/jsg/setup.c++:481: error: CODE_MOVED for unknown code block?
worker-router-worker-1  |

worker-router-worker-1  | ✘ [ERROR] workerd/jsg/setup.c++:481: error: CODE_MOVED for unknown code block?
worker-router-worker-1  |
worker-router-worker-1  |   workerd/jsg/setup.c++:481: error: CODE_MOVED for unknown code block?
worker-router-worker-1  |

worker-router-worker-1  | ✘ [ERROR] workerd/server/server.c++:2838: error: Uncaught exception: kj/compat/http.c++:1725: failed: expected headerBuffer.size() < MAX_BUFFER [131072 < 131072]; request headers too large
worker-router-worker-1  |
worker-router-worker-1  |   stack: /usr/local/lib/node_modules/wrangler/node_modules/@cloudflare/workerd-linux-arm64/bin/workerd@265008c /usr/local/lib/node_modules/wrangler/node_modules/@cloudflare/workerd-linux-arm64/bin/workerd@2652620 /usr/local/lib/node_modules/wrangler/node_modules/@cloudflare/workerd-linux-arm64/bin/workerd@2656798 /usr/local/lib/node_modules/wrangler/node_modules/@cloudflare/workerd-linux-arm64/bin/workerd@2622b74
worker-router-worker-1  |
[mf:err] Error: Network connection lost.
[mf:inf] GET /terms 500 Internal Server Error (88ms)
```
Individual URL for the host (eg. front-end) works fine from Docker.
Not exactly sure what the `headerBuffer.size()` and where that could be? Could this due to some host settings within Docker?

**Comment by johnpyp** [comment]
I'm also getting this error, but not just in Docker. It seems to have been introduced in wrangler 3.18 or 3.19, as 3.17 does not have this issue for me.

**Comment by adronitis** [comment]
> I'm also getting this error, but not just in Docker. It seems to have been introduced in wrangler 3.18 or 3.19, as 3.17 does not have this issue for me.

That's strange, our Docker env was using 3.17 but still got this error.

**Comment by kentonv** [comment]
This message is not really an error, at least not one that's relevant to most people. This is another example where our logging is highlighting bugs meant for the workers runtime team to look into. In this case V8's API for mapping JITed memory in order to construct stack traces isn't working the way we expect. This has been firing occasionally for a long time. There's actually no impact for workerd users since this information is only used when generating crash dumps in our internal codebase.

**Comment by johnpyp** [comment]
Hmm, for me it's the only noticeable difference between my worker responding on 3.17 and hanging on 3.19. Maybe it just coincides with another breaking change rather than the cause?

**Comment by MattIPv4** [comment]
👋 If it helps in debugging this, I'm reliably seeing this for one set of our tests w/ Miniflare: https://github.com/cdnjs/api-server/actions/runs/7440877000/job/20242359379

**Comment by kentonv** [comment]
TBH we should remove the logging for this error as it's unlikely anyone is going to spend time debugging it... it just doesn't matter that much.

**Comment by tddschn** [comment]
I got the same `workerd/jsg/setup.c++:481: error: CODE_MOVED for unknown code block?` error when running `wrangler pages dev ./build` on 3.22. 

Pages site is not served, got thousands of 500 internal server error lines.

**Comment by kentonv** [comment]
@tddschn Sorry, the CODE_MOVED message has nothing to do with any other problems you're seeing.

**Comment by KeKs0r** [comment]
I am starting to see them more often in CI and they seem to coincide with some process crashing. Since whenever I see these, my tests timeout. I know most comments indicate, that they should not be relevant, but could we get some more background info?

**Comment by adronitis** [comment]
> I am starting to see them more often in CI and they seem to coincide with some process crashing. Since whenever I see these, my tests timeout. I know most comments indicate, that they should not be relevant, but could we get some more background info?

Same here, we concluded the same results. But yeah more background info would indeed be nice.

**Comment by Zxilly** [comment]
got the same error with wrangler 3.39.0
<details>
import { Router } from '@tsndr/cloudflare-worker-router';
import { md5 } from 'js-md5';

export interface Env {
  IMG_BUCKET: R2Bucket;
}


const router = new Router<Env>();

router.put('/:name', async (ctx) => {
  const name = ctx.req.params.name;
  const hash = md5.create().update(name).hex();

  const bucket = ctx.env.IMG_BUCKET;

  await bucket.put(hash, ctx.req.raw.body);

  const url = new URL(ctx.req.url);
  url.pathname = `/${hash}`;

  return new Response(url.toString(), { status: 201 });
});

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    return router.handle(request, env, ctx);
  }
};
</details>
