### ISSUE TITLE
🐛 BUG: Error when importing cloudflare:sockets from a script in a subfolder (scriptPath: "./dir/script.mjs")

### ISSUE THREAD

**Issue by izidormaklary** [cloudflare/workerd#1675]
### Which Cloudflare product(s) does this pertain to?

Miniflare

### What version(s) of the tool(s) are you using?

3.20240129.2 [Miniflare]

### What version of Node are you using?

18.16.0

### What operating system and version are you using?

Mac Sonoma 14.1.1

### Observed behavior

Miniflare errors when trying to dynamically import the ```cloudflare:socket``` built-in module in a script that is nested in a directory. 

So in a ```new Miniflare```, a worker  config including  ```scriptPath:  "./script.mjs" ``` the dynamic import would work,
while  ```scriptPath:  "./dist/script.mjs"``` would cause it to crash:  (```No such module "dist/cloudflare:sockets```).

### Expected behavior
Builtins should not be imported from the directory defined in ```scriptPath```. 
(works well when the miniflare script is in the same directory as the script. 

### Please provide a link to a minimal reproduction

https://github.com/izidormaklary/miniflare-v3-monorepo-issue/tree/cloudflare-builtins-issue

### Please provide any relevant error logs

```Error: No such module "dist/cloudflare:sockets".```

**Comment by kentonv** [comment]
I think a work-around might be to prefix the module name with a `/`, like: `import * from "/cloudflare:sockets";`

@jasnell do the module registry changes you're working on fix this?

**Comment by izidormaklary** [comment]
Thanks @kentonv but in my case the import is inside a package. So I just copy the builds of the internal packages I need into the miniflare directory, which is not the best but at least there won't be an unnecessary patch once it's fixed.
