### ISSUE TITLE
Static binary?

### ISSUE THREAD

**Issue by jbergstroem** [cloudflare/workerd#174]
I think distribution and overall usage would benefit from shipping `workerd` as a static binary.

Refs: #46, #170, https://github.com/cloudflare/wrangler2/pull/2173

**Comment by kentonv** [comment]
Static binaries on glibc-based systems cannot do DNS lookups, which we need to be able to do, so a purely static binary isn't an option. However, I agree that we should statically link everything other than glibc. (glibc itself has a very stable ABI, so this should be good enough to get all the advantages of a static binary.)

**Comment by vlovich** [comment]
FWIW, Matt D is having a problem installing workerd by way of miniflare:
```
npm ERR! node_modules/workerd/bin/workerd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by node_modules/workerd/bin/workerd)
npm ERR! node_modules/workerd/bin/workerd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by node_modules/workerd/bin/workerd)
```

He's on Ubuntu 20.04 which admittedly very old. Does it make sense to at least distribute workerd built against a very old glibc to ease compat issues like that.

**Comment by jbergstroem** [comment]
> Does it make sense to at least distribute workerd built against a very old glibc to ease compat issues like that.
Simple install scripts that does a local check or two could be another way to work around issues like these.

**Comment by penalosa** [comment]
I think Ubuntu 20 has other problems (I don't think you can easily install the right libc version). Ubuntu 22 is probably the best bet for now, until there are static (ish) binaries that can be built against an old glibc

**Comment by fhanau** [comment]
As of the latest workerd and wrangler releases, we now statically link libc++ and dynamically link against glibc 2.31. While it is not a fully static build (libc, libm and pthread are dynamically linked), it should fix the issues with library versions on at least Ubuntu 20.04 and Debian Bullseye.

**Comment by kentonv** [comment]
@fhanau Nice work!

Dynamically linking against glibc (at an older version) is the right thing to do. Statically linking glibc would lead to problems with DNS lookup and other functionality which glibc itself loads dynamically. So it sounds like we're at the right end state now.

**Comment by sr229** [comment]
This thread is very old but would it be wise to static-compile it against libc musl instead? This should allow not only Alpine install capability but would allow the project to produce static deliverables.
