### ISSUE TITLE
🐛 Bug Report — Runtime APIs - FTS5 authorization needed

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/workerd#1760]
According to https://github.com/cloudflare/workerd/pull/619/files#diff-3009a3da17d76a94673aa828ce6c364fc24e34d889b4995adfc249a0e2a3c754 we're looking for the exact string `fts5` when working out if a command is allow-listed. 

It should probably be case-insensitive?

**Comment by geelen** [comment]
Should be as simple as making this comparison case-insensitive: https://github.com/cloudflare/workerd/blob/d8ffd3de075ad5dba5b5d072165c9e1830586695/src/workerd/util/sqlite.c++#L658

I'll jump in and fix it next time I'm in there, unless someone gets to it first.
