### ISSUE TITLE
URLSearchParams behavior inconsistent with spec, browser, node.js

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/workerd#1777]
The following code:

```js
 new URLSearchParams(new URL('https://example.com/?q1=foo&q2=foo+bar&q3=foo bar&q4=foo/bar').searchParams).toString();
```

...returns the following on Workers:

```
q1=foo&q2=foo+bar&q3=foo+bar&q4=foo/bar
```

...but in Node.js, browsers, etc returns:

```
q1=foo&q2=foo+bar&q3=foo+bar&q4=foo%2Fbar
```

`/` instead of `%2`

We need to understand why this is the case and if a regression from https://github.com/cloudflare/workerd/pull/1273

**Comment by anonrig** [comment]
This was indeed a bug with Ada's character sets. I've fixed it and will include this in v2.7.7

**Comment by jasnell** [comment]
Fixed with #1778

**Comment by Kaelten** [comment]
This impacted our workers in a high severity way.  @jasnell any idea how long this fix will take it to reach production?  We need to understand if this is somethign we need to work around in the short term or not.

**Comment by jasnell** [comment]
We ought to be able to get an update out fairly quickly. Let me look into it

**Comment by jasnell** [comment]
Issue closed automatically because the workerd pr change landed. Working on updating the internal repo now and will update once the fix has rolled out to production.

**Comment by jasnell** [comment]
@Kaelten ... let me know if you happen to spot anything else. We updated to use ada-url now under the covers which gave us a huge boost in both performance and spec compliance but it appears this one was missed to a gap in the test coverage (the web platform tests don't seem to even cover this particular case, which is fun). Overall, however, the implementation should be even more spec compliant now as a whole.

**Comment by ldileonardo** [comment]
This was deployed to production. Any reason this did not appear in the change log?

https://developers.cloudflare.com/changelog/?product=workers

**Comment by jaswrks** [comment]
@jasnell @ldileonardo 

```
console.log(new URLSearchParams(new URL('https://example.com/?sort=date%3Adesc').searchParams).toString());
```

Returns the following in Node and in browsers:
https://jsfiddle.net/jaswrks/a0x3j8L6/1/

```
sort=date%3Adesc
```

On Cloudflare workers it [returns](https://workers.cloudflare.com/playground#LYVwNgLglgDghgJwgegGYHsHALQBM4RwDcABAEbogB2+CAngLzbPYDqApmQNJQQBimYACFKNRHQDsABgBsATQDiAGSUBRXAA0FwAOaoNASQBcLFh268BWEdVqTZileq279BgLAAoAMLoqEdn9sABEoAGcYdDDeKD8jEgwsPAJiEio4YHYGACJ8QgA6ACsw7NJUKDBAjKzclKKSr19-QIhsABU6GHZ4uBgYMCgAYwJYqmRCuAA3ODDBhFgIAGpgdFxwdi8vdgAPSKQSXHZUOHAIEgBvTwBIdMz47NVtjP72EgBBAAUDbIAaa8IdGF4gBtbI7Z6VX4kbK9KBQ7IIdgRPxhdjZAC6fwAvkRPF5TMxzDx+IIbGJ6NJ5Mo1JptHpDI0-AEgqFkdFoHEEoJkoRSLcalAaDt6qUEhUqpkcoLDtsRYzmkEOl0en0BsMOWMJtNZvMYEsVmtKptPDs9mdDsdThdrjM6FRBgl2BBBgALAAUiIAjiAkRAfiRApN-YMINsAJTWq5XREQEAIKhpdgAdxIACUkZEqKi3VRkyQAKqppQAZXYiFdH0QGTCObzhaUboA5C6IBAYEDkMhwcAXvlBuhgMgAPxhTAQBh5dgAUgAzG9DrNG2H8qjyy7Kwhq8uIOhixB5lQdG6w2HcVcsdjcfiCUTLKTRHZKY4aS56R4fEyWiFwpF2aN4okOB5Kk-I5Em7BgP2mT5C2wBgKK5SVKB2TgZBA7sDBEBwdk8rMq0SrdCQATbCg-RwIKxoADwAITBAA8t4bRyB8qgkLBYAAHyeJR7EkGAcCHjkgTZFxVw8WWuCiWJmSECQrqIKi47ZPmbR8NgAAc2QkMgUmUTJcBsa2MDYOw3pQJMOQaNg+ZvNgvg9iMZCQnJn7+DkBiqAw7C4DoaLabp+lpNUOSTFAyZmlp-YKkpSZQLgEAuhO7ChYM7DYLF8Uuv6goxHAYDYLMeVZAAjPkUhaTp1xidAECVBx3hgJQuCoPxiIkKwmAANbsAgYQkB8-F0DoCAPpRyA1XVVWUQMVCdVV0YQTkYQQHQlRhC67BOtk80uoiqA5C2bYdsgZFDSNtj5IckwwCNuB9o1IDNa1GFXcgqFQWly2rRhgxhCUVWVWJyAbXAkmeNclEULgdC6bg5lyfxf05C1iBIiJ82UVAugkGECCDAdRnHadw0PpdyU3as91NSjiJk5MaDPWE+QwIeFW6cgcOTAF5FUFJYmcwjMxhGBXU9WE2CNTo6AiWNnN85RMB81cHBoZk1EFqiREuuE-WDSTthEegRG+gc8yTK8BkdQg3UIMGiIEBbBzsCshvzVc62oyQfgzew-oCbgJBJhtCb29DTv9OgdAHFAiIhmAUc7lrrzeb55BR4p0CHiQIAwCQcBuw11PPXngz9tQED5BjJ3yy6xUcawLoECQOuW6LCBDmNtfy4rbtvCQhePTTrxWzbzd9QAUlMcDFnMCwuYcJB0JQgfzAEWtN43NBrYvlAIIHnBu+y7CNn1AASbRtB8RGbqg5QOnDse1VHgr9w9T2oyfAY+a8jXqqMfWIAfEnN2SZMBgFwH7MAjVYpZyXiAQ2fF0DqleP2BegxGqa0TnAvegQA4gFRL1ZuCZMCHD3juN2iJkQ0AQQlZ2JAVhtTMoMTq8cq49yjGJLubR6DNzONg1EYBUCdzrhjdhHC6IJmwXxI4ZwW44whMPNu69ZF9QQNQKggodBewTAlHWR98gkDkMvYYVA3beV4Lwvi5kLbUNRK8WhJBKGnD6htWmJB1AWIcfABKecKDmwQcgWErsOHu02mxdAKYHHdheO1JRm9cDbzhrfHqLRHGUACEzQxxiBJ5zAKOL+vA3YONQfYo2djA6NwgJ-X80QnI2IDmQA8WipG5hIs3Q4BlE4DFQBhNh7NgA81EmNKGMNuLAywpxPEngCRsE4MSKwwgHziCfNSZwdI3C4S-KyX8MROSAR5CBYK2R9LAQQuKZCTl0BkBwh+aK7ROiEV6P0IYIw-DjFHFQY05xshQW8VAMgFReB0AAPqTmyEYbIAAmKQkKAAs2ApAzgRRIX4PyBx-IBQMFawKUaAnBaCKgqx2DFGBb8ggGIfjHJ5sCg06xwXZGlMKYo2QsTXlMLeEk1glkUgcKs2krhDDMC8EAA):

```
sort=date:desc
```
