### ISSUE TITLE
Types regression: 2nd argument for `DurableObjectNamespace.get()` is gone in worker-types `4.20240402.0`. (prevents passing `locationHint`)

### ISSUE THREAD

**Issue by feychenie** [cloudflare/workerd#1953]
After updating `@cloudflare/worker-types` to latest (`4.20240402.0`), `DO_namespace.get(id)` does not accept a second parameter for options anymore, while it is still documented as possible in the published docs.

Edit: it's still the case in the `4.20240403.0` update.

![Screenshot 2024-04-03 at 19 09 59](https://github.com/cloudflare/workerd/assets/277455/f471c831-887e-49dd-975b-ec7c79a88998)

![Screenshot 2024-04-03 at 18 17 59](https://github.com/cloudflare/workerd/assets/277455/b561181e-3004-41ec-9e69-7b9ef57605ac)

**Comment by kentonv** [comment]
@mrbbot I think this might have been broken by #1870, which added type overrides for `DurableObjectNamespace` that are missing the second argument to `get()`.
