### ISSUE TITLE
cannot deploy Python Workers that depend on packages defined in requirements.txt

### ISSUE THREAD

**Issue by schunlee** [cloudflare/workerd#1995]
npx wrangler@latest deploy
 ⛅️ wrangler 3.48.0
-------------------
▲ [WARNING] The entrypoint src/worker.py defines a Python worker, support for Python workers is currently experimental.

Attaching additional modules:
┌─────────┬────────────────────┬──────┐
│ Name    │ Type               │ Size │
├─────────┼────────────────────┼──────┤
│ fastapi │ python-requirement │      │
└─────────┴────────────────────┴──────┘
Your worker has access to the following bindings:
- Vars:
  - MESSAGE: "This is an environment variable"
Total Upload: 0.90 KiB / gzip: 0.43 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/23a0e6101*******/workers/scripts/hello-fastapi) failed.

  You cannot yet deploy Python Workers that depend on packages defined in
  requirements.txt. Support for Python packages is coming soon. [code: 10021]
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

**Comment by dom96** [comment]
From your output:

> You cannot yet deploy Python Workers that depend on packages defined in requirements.txt. Support for Python packages is coming soon.

This feature is not available yet, but will be soon.
