### ISSUE TITLE
Introduce --nodejs_compat_unleashed runtime flag

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workerd#2133]
As we improve our node.js compat story, it would be great have a runtime flag that offers a more "aggressive" and compatible version of `--nodejs_compat` runtime flag. We could call this flag `--node_compat_unleashed` or similar.

This new flag should expose supported node builtin modules without the `node:` prefix, and should also expose globals like `process`, `Buffer` on `globalThis`.

We can then test with this flag, and at some point in the near future, this flag would be activated via a compat date as long as `nodejs_compat` is present (essentially making the existing `nodejs_compat` become `nodejs_compat_unleashed` once the compatibility date is reached or exceeded.

Originally proposed in https://chat.google.com/room/AAAAZwUYa48/4rD9Yjauj9w/yE5EU56IaRg?cls=10

**Comment by kentonv** [comment]
Bikeshed comment: The name "unleashed" sounds a little, uh, silly to me. Maybe `nodejs_compat_no_prefix` or `_no_namespace` or something?

**Comment by IgorMinar** [comment]
I'm not attached to the name. The flag should in addition to unprefixing modules also introduce node's globals, so `no_prefix` seems not comprehensive enough.

**Comment by jasnell** [comment]
heh, yeah, I wasn't going to go with "unleashed" ;-) ... I'll be working on this in the coming couple of weeks, want to get the `Request.cache` stuff done first, then will do this next.

**Comment by jasnell** [comment]
Initial draft implementation in #2147
