### ISSUE TITLE
🐛 BUG: `ForwardableEmailMessage` is missing `reply` from its type definition

### ISSUE THREAD

**Issue by charliez0** [cloudflare/workerd#2283]
The `ForwardableEmailMessage` interface is [defined](https://github.com/cloudflare/workerd/blob/6ac4ba0296a9d83a96019e2f3ebc44c562b7e660/types/defines/email.d.ts#L18-L44) as follows:

```
interface ForwardableEmailMessage extends EmailMessage {
  readonly raw: ReadableStream<Uint8Array>;
  readonly headers: Headers;
  readonly rawSize: number;

  setReject(reason: string): void;
  forward(rcptTo: string, headers?: Headers): Promise<void>;
}
```

As per https://developers.cloudflare.com/email-routing/email-workers/runtime-api/#emailmessage-definition this type definition should also include a `reply` method: `reply(message: EmailMessage): Promise<void>;`, but it doesn't.

If the docs are the correct source of truth, we should update the `ForwardableEmailMessage` type definition to reflect that.

**Comment by CarmenPopoviciu** [comment]
hi @charliez0,

can you please use our issue template to provide more details about the issue you are reporting? it is very hard for us to address any issue without a proper understanding of it.

thank you

**Comment by charliez0** [comment]
> hi @charliez0,
> 
> can you please use our issue template to provide more details about the issue you are reporting? it is very hard for us to address any issue without a proper understanding of it.
> 
> thank you

the issue template is empty, idk why

L4285:4311
```typescript
declare interface ForwardableEmailMessage extends EmailMessage {
  /**
   * Stream of the email message content.
   */
  readonly raw: ReadableStream<Uint8Array>;
  /**
   * An [Headers object](https://developer.mozilla.org/en-US/docs/Web/API/Headers).
   */
  readonly headers: Headers;
  /**
   * Size of the email message content.
   */
  readonly rawSize: number;
  /**
   * Reject this email message by returning a permanent SMTP error back to the connecting client including the given reason.
   * @param reason The reject reason.
   * @returns void
   */
  setReject(reason: string): void;
  /**
   * Forward this email message to a verified destination address of the account.
   * @param rcptTo Verified destination address.
   * @param headers A [Headers object](https://developer.mozilla.org/en-US/docs/Web/API/Headers).
   * @returns A promise that resolves when the email message is forwarded.
   */
  forward(rcptTo: string, headers?: Headers): Promise<void>;
}
```
missing reply() attribute

**Comment by charliez0** [comment]
@CarmenPopoviciu

**Comment by charliez0** [comment]
any progress?

**Comment by CarmenPopoviciu** [comment]
hi @charliez0,

thank you for providing the clarifying details. I understand now what the issue at hand is and have updated the GH issue title/description to reflect that. 

I've assigned the issue to myself, and should have a fix PR up this week! I'll update here :)

**Comment by CarmenPopoviciu** [comment]
> If the docs are the correct source of truth

they are, I checked!

**Comment by CarmenPopoviciu** [comment]
this fix should be out with the next `workerd` release, and available in `workers-sdk` with next week's release 🎉 

thx again @charliez0 for reporting this <3
