### ISSUE TITLE
🐛 BUG: Durable Objects: `ws` argument in `webSocketClose()` handler is invalid

### ISSUE THREAD

**Issue by majames** [cloudflare/workerd#2299]
### Which Cloudflare product(s) does this pertain to?

Other

### What version(s) of the tool(s) are you using?

`wrangler@npm:3.60.3`,  `@cloudflare/next-on-pages@npm:1.11.3`

### What version of Node are you using?

`20.13.1`

### What operating system and version are you using?

MacOS

### Observed behavior
In development when I log the `ws` passed to `webSocketClose` the result is:

```
WebSocket { extensions: '', protocol: '', url: null, readyState: 2 
```

### Expected behavior
The `ws` passed to the close handler to have the correct url.

### Steps to reproduce

```typescript
  async webSocketClose(ws: WebSocket) {
    console.log(ws);
  }
```

At this stage it's unclear to me whether this is also an issue when in prod (i.e. running on cloudflare)

**Comment by MellowYarker** [comment]
I'm inclined to agree with @threepointone. It's not really clear when we would set it on the server side with `new WebSocketPair()` and the URL you use to connect to a Durable Object doesn't need to be the same as the URL used to connect to the Worker. Using `.serializeAttachment()` sounds like the right approach here.

**Comment by majames** [comment]
Thank you both for your clear responses. In my case I was able to retrieve the data I needed from the associated websocket via [`getTags()`](https://developers.cloudflare.com/durable-objects/api/websockets/#gettags).

The `serializeAttachment()` also sounds like a great approach if i didn't already have the required data in a tag. Thanks!
