### ISSUE TITLE
🐛 Bug Report — Runtime APIs TextDecoder

### ISSUE THREAD

**Issue by charliez0** [cloudflare/workerd#2300]
TextDecoder does support `new TextDecoder("utf-8")` but does not support `TextDecoder("UTF-8")`

**Comment by fhanau** [comment]
Thank you for reporting! You're right, based on the [Spec](https://encoding.spec.whatwg.org/#names-and-labels) upper-case labels are to be supported too.

**Comment by fhanau** [comment]
Fix has been merged – unfortunately I'm not sure if this will make it to the next production environment release, so deployment might take a while.

**Comment by fhanau** [comment]
Update: The fix has been deployed to the production environment since Tuesday 7/2. Thanks again for reporting this!
