### ISSUE TITLE
🐛 Bug Report — Runtime APIs -- Fetch extremely slow and errors

### ISSUE THREAD

**Issue by dsmmcken** [cloudflare/workerd#2343]
Running the example fetch from docs errors and is extremely slow, both deployed and when run with wrangler and leaves errors in log.

```
async function getJson() {
  const url = "https://jsonplaceholder.typicode.com/todos/1";

  // gatherResponse returns both content-type & response body as a string
  async function gatherResponse(response: any) {
    const { headers } = response;
    const contentType = headers.get("content-type") || "";
    if (contentType.includes("application/json")) {
      return { contentType, result: JSON.stringify(await response.json()) };
    }
    return { contentType, result: response.text() };
  }

  const response = await fetch(url);
  const { contentType, result } = await gatherResponse(response);

  const options = { headers: { "content-type": contentType } };
  return new Response(result, options);
};

console.log("Get JSON");
const json = await getJson();
console.log("Got JSON");
```

Takes multiple seconds to return.

```
Get JSON
✘ [ERROR] Uncaught (async) Error: internal error

Got JSON
```

Tried various other URLs, and it's slow regardless of the endpoint. Why is fetch slow and returning errors?

My end goal is to just fetch something from r2, but it's so slow its unusable.

**Comment by kentonv** [comment]
Here:

     return { contentType, result: response.text() };

You are missing an await, it should be:

    return { contentType, result: await response.text() };

Additionally note that this line:

      return { contentType, result: JSON.stringify(await response.json()) };

seems to be needlessly parsing the JSON and re-serializing it, wasting time, although not much time if the JSON is short.

> [ERROR] Uncaught (async) Error: internal error

I cannot reproduce any error. The code seems to function fine (except it returns the text `[object Promise]` in the non-JSON case).

> Takes multiple seconds to return.

I cannot reproduce this, the code seems to be dominated by the time it takes to contact the origin server (which even then is well under 1s). Less than 1ms CPU time used. Perhaps there is something wrong with your internet connection?
