### ISSUE TITLE
🐛 Bug Report — Runtime APIs - Workers TCP 连接断开以及连接数限制问题

### ISSUE THREAD

**Issue by syf-work** [cloudflare/workerd#2356]
本地调试 cloudflare workers，用 socket runtime api `connect` 创建 TCP 连接后。有以下两个问题：
1. 调用了 `socket.close()` ，抓包发现 worker 并未发出 **FIN** 信令, TCP 连接无法断开 。
2. 上线后，成功创建了 5 次 TCP 连接，发送请求并收到响应，到第 6 次的时候就卡住了。

下面是代码的解释，注意看里面的注释：
![image](https://github.com/cloudflare/workerd/assets/103098522/4b9ffc08-69ae-4099-a929-de7ce7923ed0)

这里是本地调试，抓包的截图
![image](https://github.com/cloudflare/workerd/assets/103098522/13699b54-3b57-43f9-abcb-a8b9a07cc348)

**Comment by YJWang666** [comment]
This is the translated version of above issue
----------------------------------------------
The customer developed and debugged  Cloudflare Workers locally，and after using socket runtime api connect to create TCP connection, 2 issues identified -

1. Calling socket.close(), packet captured shows that the Cloudflare Worker did not send FIN,  and the TCP connection cannot be closed.
2.After going live, successfully created 5 TCP connections, able to sent requests, and received responses. However, it got stuck on the 6th connection attempt.

Attached screenshots above are 1） comments of the code   2) packet capture collected during local debugging
