### ISSUE TITLE
🐛 BUG: TCP Stream read() function gets stuck

### ISSUE THREAD

**Issue by JamesDelfini** [cloudflare/workerd#2366]
### Which Cloudflare product(s) does this pertain to?

Workers for Platforms, Workers Runtime

### What version(s) of the tool(s) are you using?

3.18.0 [Wrangler]

### What version of Node are you using?

v20.11.0

### What operating system and version are you using?

Windows 11

### Describe the Bug

After performing a write operation and expecting a response, the issue arises when calling `read()` again. It gets stuck in this scenario.
```javascript
import { connect } from 'cloudflare:sockets'

const socket = connect(...);

socket.writable.getWriter().write(...);
const { value: bytesRead } = socket.readable.getReader().read(); // Valid: Expected a response from the server
// Tries to read again to reproduce the behaviour
socket.readable.getReader().read(); // Invalid: The program got stuck here and there are no returns or error throwns
```

**Comment by dom96** [comment]
@nicolasbeauvais why do you expect it to return `done: true`? In your example the server keeps the connection open, so the socket isn't closed immediately after the data is sent. If you add a `connection: close` header [then it doesn't get stuck anymore](https://workers.cloudflare.com/playground#LYVwNgLglgDghgJwgegGYHsHALQBM4RwDcABAEbogB2+CAngLzbPYDqApmQNJQQBimYACFKNRHQDKAcwAiAQQBqfBXICsAGTJgFrIQHEAXCxYduvAVhHVak2YuVrN23XoCwAKADC6KhHa-sGSgAZxh0YN4oHwMSDCw8AmISKjhgdgYAInxCADoAK2CM0lQoMH9U9KzE-MKPb19-CGwAFToYdhi4GBgwKABjAiiqZDy4ADc4YL6EWAgAamB0XHB2Dw92AA8wpBJcdlQ4cAgSAG93AEgUtJiMgFEN1J72EjkABQBJDIAaC8IpYJiAG0MptHmVviQMl0oBCMgh2KEfMF2BkALo-AC+RHcHmMzFMPH4gisYno0nkShUGi0On0dR8fgCQUREWg0ViggShFIV0qUBomxqRVipXKaUy-L2GyF9IaAVa7U63V6AzZw1GEymMxg80WyzKa3cUGA22OJxIfR8VHYfWOGNiCHQwBIAHI+mBKLhUGBEB1gug+gBrdgQYIu9zuTam3b7Q6QU4XSZ0Kh9WIhvoACwAFPCAI4gBEQL4kfxjYu2jYASgT53OlqowWOGfCEF5JAYrowvmCOX+hGgfRyluA4dr9cbJHgEAz7ddyGCyB9EHQyDGACYACzICQANhAdAA7huhABZACqzVeAAk8hsNweABpSHIH9CoVBr8MRsdI47+oMhrO9bWraWZnLW5zNo2vI-BBpoxAAHAADBc5wYpW351r+JAHjMfgILO-7BhAL54XAWjsL2IasHh7AIFmGE-g2xz+JaewER21oHiQzSbBAtwpksdEMah44sYJey4LOrFCQgOQyXsWYAAZ6LczQkAAJCcU4ZvaV7NJeyAAIw5EZAA6CBmVQV4tjEWlQa2FQYhZVn1CBaoxO64TsC5VC+UpjHnHAB5wLwOG0XJuG8OwWYKewuAYahyAAFTJahJDJTxGYhBaQk4ZggYitaJBQKgJA+GAdDlcV8JwFJOX+JQUgzsuJBSIB07PKg4BgCQ8KIg2zz1oyRbpZlZAgMcpUkHAJDIvWUm1fVwTJDaCLBOIxadSQHroDAOGlL1VDoOJUk+CQ20+hOmbUIVcA0GNF0zFI7UEbNwQgMq7BpL44h9ewdUXRmBBtSGK2NiAQY5GNyCoXEM0hWFWZiRaGa3eVZVESGORLeRZQ5DAsDsM0GaOiAzVZlxPF8TINqyRIEC1cADGVtW4FMf6+MelIyNo1QgaBRimFYyRXnIiJqHwhAIAIFQq3cQASgiYSDVmLroIGLqVtiaGYtiuJ4gS5jEqINjkvYVJOLSbheAyjSBCEYSskMMRxDg2RJLymQHuwYDDpRGYQMAYDCiUZRexkPt+06AdByHsojS0bQdBdfHID0oVUIaAA8ACEMgAPKeM0ACary3CQgfBwAfO42dV71PpUFImT+BktfnPXAO4B3ndpIQqOIMiECZBefDYAhGQkMgvfZ-3s2BxAMDYOw+ZQGMmQPtgZ5yNg3gmoMFFT8NjSZO8twMPF7VTzPqFzyGs0R2MUDsAeprH3bvje1AuDTgwezPz6OwbAB4f7TmLPySIcAwDYCmNA9IJkkI31ntACAZRq6eA9CAL0Pp4QkFYAVOiK1Xg+joFIMmNBs7IFQegu+vR+aoXOPCMAmRGx0DKMEDM7AQwZEYaTfYmRF4wABMgdOpDyGmxyAAmAjpcBDiwTg30Uj2BjGQFHf2sCIDsMon0YIhQkodyoVwuqtcLjZwoLgOgs9cDrwtFdYImRvS+kKL3TuxopBzQQH0QREAl4iLEXAMhFC5HSNkfIz0Tj4TKNUZEhEBNm7ILvsgGxYxZ7AEzq47OKS7GTAcZHQhCBgjYG5ugduVCUmZJgK484HBo5pFziQM8yIgY5RIYEiR1gLroFThOXAMwxjPFmgQhAwYEDllqn4GaMZFhdMYecThvpqr0PYMWe6UkDxcLlktKqewejoB2VAeEtpKpdKBs8K+zwyBVWHtAZuJBPozTmZgiJuDBl9EtNQEijCqFVO+RmIy1dWDAymitIZBSAD8RiAXfN+RBc4cgSDPOwbE-BBSSorQAFLjDgBIaYsxcp7BIHQSg4VopAxBsDGgHCiWUAIj7MgczWTsBdCtfSl4npwHfP0XYhybRoKqvyRFCjYkspLLgdqO0AyDCRDNYJZy5mvgQGAXAqywAelAXc4lIBTkelVENPKYtnitS1QRfwUkQDIkKSVOWmB2KzLhf1FWUlWqdWdIsPBa8gyVW+enTJ-zq7NHoCVY4JrkRgFQFCyp1SC5yxNTtfYIKpkbRNGUVFIy6LksTQgagVB+QePOtOHKTKcgkBLiSgYVA5nxTCmFXoAyZo0Dmtws5-0PqQBWlwqJJBbg2OONtHSM0KD1tasgaE9qILImeM2bi21QQpueMM0Zlc1nUpse+OijQ+qUD8D2Ut5b7ozTAP6MVvA5nbTYka7pk6cLAtFU7CIFEG1STIDMTVtLVobCmnsWarVeioEoj62FndkDpP5IY5AFirF12QA3WuBtjBGyJJYU24hzaUkcDSFwCd7bMidpEdkbsuSewqJkeeHtQ6igjlodAZAMjYflMnJUPR+jSvVP6LOOJ3AnAyMOKcUAyClF4HQAA+tkFEBgMhriQpubASEADMsmADs3weNOj4wJ3oWjhNOP+BkAwwJjp7AKMJ3jBA0RfAyKBqgwm9QrD0xkSUgoCgZAxPBkwnBCQWGEChskdh0PUmcPoZgHggA).

**Comment by nicolasbeauvais** [comment]
Thank you for fixing my playground example @dom96, the `read()` behaviour makes more sense now :bow:
