### ISSUE TITLE
R2 Object `body` missing `clone()` function type

### ISSUE THREAD

**Issue by chrisspiegl** [cloudflare/workerd#2453]
I wanted to use an r2object body twice.

I am aware that with a fetch() response, we can use `.clone()` to do this.

When I tried, `r2object.body.clone()` types suggest that it's not present.

**Previous Statement:** ~~When running the code, it does work as expected, giving me the feeling that the type definition for `clone()` is missing.~~

**Correction:** It appears that the `clone()` function indeed does not exist. But maybe it should.

![CleanShot 2024-07-28 at 15 08 10@2x](https://github.com/user-attachments/assets/e0d905f3-144b-41ed-b83c-752eb46ff2cc)

**This is a minimal code:**

```js
r2object = await env.MAIN_R2_OLD.get(cacheKey)

if (r2object) {
  ctx.waitUntil(env.MAIN_R2_NEW.put(cacheKey, r2object.body.clone(), {
    httpMetadata: r2object.httpMetadata,
    customMetadata: r2object.customMetadata,
  }))
}

return new Response(r2object.body, init)
```

**Comment by kentonv** [comment]
`ReadableStream` has a `tee()` method, which does what you are looking for: https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/tee

For whatever reason, the standards decided the method on `ReadableStream` should be called `tee()` instead of `clone()`. (The `clone()` method appears on the HTTP `Response` type, but R2 does not use this type.)

**Comment by chrisspiegl** [comment]
Thank you for your detailed response. Then I'll soon close this issue again.

One more question if I may: `tee()` returns an array of two copies of the stream, would it be possible to still use the one that's the original `r2object.body` or is that “used” at that point?

Cause handing over the “split” stream is another step compared to the ease of use of the `response.clone()` variant.

**Comment by chrisspiegl** [comment]
Thank you for this information. With that, I'll close this issue, as I do not expect the `clone()` to be added to the r2 response body. Considering, it will stay a standard stream.

The workaround for using a r2 body twice is to use `const [body1, body2] = r2object.body.tee` to split the stream into two, and then do whatever needs to be done with those two streams.
