### ISSUE TITLE
The `request` type inferred from `ExportedHandler` is `any` instead of `Request`.

### ISSUE THREAD

**Issue by tavoyne** [cloudflare/workerd#2474]
![image](https://github.com/user-attachments/assets/c99a1b1c-c6e5-4b48-9da3-bbae76da3e81)

**Comment by petebacondarwin** [comment]
Can you provide a reproduction (perhaps git repository) that we can use to diagnose this problem?

**Comment by asimpletune** [comment]
I am having the same issue right now. For me `@cloudflare/workers-types@4.20231121.0` + ` wrangler@3.21.0` were definitely working, and I see this issue appearing with the at latest `@cloudflare/workers-types@4.20240815.0` + `wrangler@3.72.0`, although possible earlier.

**Comment by asimpletune** [comment]
I could be wrong but it looks like the issue was introduced about 6 months ago, here https://github.com/cloudflare/workerd/blame/a47804f8bbcd06904bb9eae91e0e6c3ffdc7f6d6/types/defines/pages.d.ts#L4. 

It looks like `Request` doesn't have generics, although they're being used here.

**Comment by penalosa** [comment]
The `Request` defined in `@cloudflare/workers-types` does have generics, so that should work, I think.

@asimpletune Would you be able to provide a reproduction repo that demonstrates the issue?

**Comment by asimpletune** [comment]
Hi! Id love to but I can't for a few weeks. But if you create a new project with the versions I listed above you will see the same results. 

Although, the version I cited is when the issue was first introduced, so it should be present with wrangler 3.72.0 and its sibling worker types file.

Otherwise I can create a new issue when I'm available again, since the issue I brought up is only similar to the OP but not guaranteed to be the same.

**Comment by yunsii** [comment]
I have encountered the same question
![image](https://github.com/user-attachments/assets/7c272608-495c-49e6-a29b-7cfb179c4914)
https://github.com/yunsii/cf-worker-status-page-pro/blob/7896301356277d72d9fc1ced420ad495547f3318/src/worker/index.ts#L24-L32

**Comment by Cherry** [comment]
There's a couple of issues with your setup @yunsii:

- Firstly, you're hitting https://github.com/cloudflare/workerd/issues/1298 and will need to pin your `@types/node` to an older version to prevent `Request` being overriden here;
```json
  "pnpm": {
    "overrides": {
      "@types/node": "20.8.3"
    }
  },
```
- Then you're also loading `DOM` types in your `lib` config in your `tsconfig`, which also has its own version of `Request`. Remove this.

After this, the `request` type works fine in your example. ![](https://i.james.pub/file/2024/09/7e418edb-2189-4039-a77d-f3a7514593a6.png)

If you have a need for `DOM` types, I'd recommend a different `tsconfig.json` for your `worker`, and your frontend.

**Comment by yunsii** [comment]
@Cherry Thanks for your detailed explanation, it is a interesting issue 😄

**Comment by lrapoport-cf** [comment]
hi all :) for anyone still running into this, please check out @Cherry 's [followup comment above](https://github.com/cloudflare/workerd/issues/2474#issuecomment-2336686532). if you are still having problems, please feel free to open a new issue referencing this one with a repro and any additional details and we will revisit and investigate. thanks!
