### ISSUE TITLE
Implement node:zlib API

### ISSUE THREAD

**Issue by npaun** [cloudflare/workerd#2486]
Implement an API compatible with [node:zlib](https://nodejs.org/docs/latest/api/zlib.html)

- PR #2477
  - [X] Create module (@anonrig)
  - [X] `crc32`  (@anonrig)
- PR #2496
    - [x] Export `zlib.constants` (@npaun)
- PR #2533
    - [X] `inflate` / `inflateSync` (@npaun)
    - [X] `deflate` / `deflateSync` (@npaun)
    - [X] `inflateRaw` / `inflateRawSync` (@npaun)
    - [X] `deflateRaw` / `deflateRawSync` (@npaun)
    - [X] `gunzip` / `gunzipSync` (@npaun)
    - [X] `gzip` / `gzipSync` (@npaun)
    - [X] `unzip` / `unzipSync` (@npaun)
- PR #2660 
  - [X] `brotliDecompress` / `brotliDecompressSync` (@npaun)
  - [X] `brotliCompress` / `brotliCompressSync` (@npaun)
-  PR #2519 
    - [x] `createUnzip` / `Unzip` (@anonrig)
    - [x] `createInflate` / `Inflate` (@anonrig)
    - [x] `createDeflate` / `Deflate` (@anonrig)
    - [x] `createInflateRaw` / `InflateRaw` (@anonrig)
    - [x] `createDeflateRaw` / `DeflateRaw` (@anonrig)
    - [x] `createGunzip` / `Gunzip` (@anonrig)
    - [x] `createGzip` / `Gzip` (@anonrig)
-  PR #2619    
    - [x] `createBrotliCompress` / `BrotliCompress` (@anonrig)
    - [x] `createBrotliDecompress` / `BrotliDecompress` (@anonrig)

**Comment by fhanau** [comment]
@npaun @anonrig feel free to assign me as a reviewer on PRs for this – I have a background in data compression and implemented Brotli support in the runtime so pretty familiar with the C API for brotli/zlib.

**Comment by npaun** [comment]
Node.js tests relevant to zlib

- [ ] test-zlib-brotli-16GB.js
- [ ] test-zlib-convenience-methods.js
- [ ] test-zlib-flush-drain.js
- [ ] test-zlib-invalid-input-memory.js
- [ ] test-zlib-sync-no-event.js
- [ ] test-zlib-brotli-flush.js
- [x] test-zlib-crc32.js
- [ ] test-zlib-flush-drain-longblock.js
- [ ] test-zlib.js
- [ ] 👉 test-zlib-truncated.js (@npaun)
- [ ] test-zlib-brotli-from-brotli.js
- [x] test-zlib-create-raw.js
- [x] test-zlib-flush-flags.js
- [ ] test-zlib-kmaxlength-rangeerror.js
- [ ] test-zlib-unused-weak.js
- [ ] test-zlib-brotli-from-string.js
- [x] test-zlib-deflate-constructors.js
- [ ] test-zlib-flush.js
- [ ] 👉 test-zlib-maxOutputLength.js (@npaun)
- [x] test-zlib-unzip-one-byte-chunks.js
- [ ] test-zlib-brotli.js
- [ ] test-zlib-deflate-raw-inherits.js
- [ ] test-zlib-flush-write-sync-interleaved.js
- [ ] 👉 test-zlib-no-stream.js (@npaun)
- [x] test-zlib-write-after-close.js
- [ ] test-zlib-brotli-kmaxlength-rangeerror.js
- [x] test-zlib-destroy.js
- [ ] 👉 test-zlib-from-concatenated-gzip.js (@npaun)
- [ ] 👉 test-zlib-not-string-or-buffer.js (@npaun)
- [ ] test-zlib-write-after-end.js
- [x] test-zlib-bytes-read.js
- [ ] test-zlib-destroy-pipe.js
- [ ] test-zlib-from-gzip.js
- [x] test-zlib-object-write.js
- [ ] test-zlib-write-after-flush.js
- [x] test-zlib-close-after-error.js
- [x] test-zlib-dictionary-fail.js
- [ ] 👉 test-zlib-from-gzip-with-trailing-garbage.js (@npaun)
- [ ] test-zlib-params.js
- [x] test-zlib-zero-byte.js
- [ ] test-zlib-close-after-write.js
- [ ] test-zlib-dictionary.js
- [ ] 👉 test-zlib-from-string.js (@npaun)
- [ ] test-zlib-premature-end.js
- [x] test-zlib-zero-windowBits.js
- [x] test-zlib-close-in-ondata.js
- [ ] 👉 test-zlib-empty-buffer.js (@npaun)
- [ ] test-zlib-invalid-arg-value-brotli-compress.js
- [ ] test-zlib-random-byte-pipes.js
- [x] test-zlib-const.js
- [x] test-zlib-failed-init.js
- [x] test-zlib-invalid-input.js
- [x] test-zlib-reset-before-write.js
