### ISSUE TITLE
🐛 Bug Report — Runtime APIs

### ISSUE THREAD

**Issue by tpasternak** [cloudflare/workerd#2540]
Hey workerd team!

I've just been trying to open the codebase with CLion on Fedora 40, and it looks like the default clang version can't build zlib with the default opts.

It looks like you have to add either `-Wno-error=register` or `--std=c++14` here https://github.com/cloudflare/workerd/blob/7aa2d5f569370b7caf3165df18233fc30be77c9d/WORKSPACE#L291-L293

**Comment by fhanau** [comment]
What clang version number are you using and does clang on Fedora add additional options such as -Werror? Any version 16+ should work, with clang-18 I'm not getting any warnings for it locally. Note that zlib is exclusively C, so there should be no need to specify C++14 here.

**Comment by tpasternak** [comment]
nvm I accidentally set --action_env=CC=clang++
