### ISSUE TITLE
Ensure CJS/MJS require interop in nodejs-compat 

### ISSUE THREAD

**Issue by jasnell** [cloudflare/workerd#2606]
In Node.js, there is now experimental support for `require('...')` an ESM.

In Node.js, by default, requiring an ESM, the require returns the module namespace. There is a new PR, however, that will allow the ESM to indicate that the require should return the default export instead: https://github.com/nodejs/node/pull/54563

Example:

```js
// a.mjs
export default class Foo {};
```

```js
console.log(require('./a.mjs'));
// [Module: null prototype] { __esModule: true, default: [class Foo] }
```

With the PR

```js
// a.mjs
export default class Foo {};
export const __cjsUnwrapDefault = true;
```

```js
console.log(require('./a.mjs'));
// [class Foo]
```

When `nodejs_compat_v2` mode is on, and we are calling `require('...')` from a CommonJS module, the new export should be honored.

**Comment by anonrig** [comment]
It seems like this is already implemented @jasnell. Can we close this?

**Comment by jasnell** [comment]
Yes
