### ISSUE TITLE
🐛 Bug Report — Runtime APIs - nodejs compat - crypto - `getRandomBytes()`

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/workerd#2716]
The `getRandomBytes()` function will fail when called if it is not bound to the `webcrypto` object.
See https://github.com/cloudflare/workers-sdk/pull/6721 for a test case.
Currently the calls fail with: `TypeError: Illegal invocation: function called with incorrect `this` reference.`.

This has been fixed in unenv via https://github.com/unjs/unenv/pull/309 but I think that the `getRandomBytes()` function should not require any particular `this` to work.

**Comment by kentonv** [comment]
What's `getRuntimeBytes()`? Did you mean `crypto.getRandomValues()`?

Assuming so, it has the same behavior in Chrome:

![Screenshot from 2024-09-16 15-47-53](https://github.com/user-attachments/assets/88c832d9-eca3-4371-ba43-5d70590071a3)

**Comment by petebacondarwin** [comment]
To be more concrete. Using `nodejs_compat` (not v2, so no polyfills) running this Worker:

```ts
import { getBuiltinModule } from "node:process";

export default {
	async fetch(
		request: Request,
		env: Env,
		ctx: ExecutionContext
	): Promise<Response> {
		const results: string[] = [];
		const nodeCrypto = getBuiltinModule("crypto");
		const webcrypto = nodeCrypto.webcrypto;
		const getRandomValues = webcrypto.getRandomValues;
		const a = crypto.getRandomValues(new Uint8Array(6)).toString(); // global
		const c = webcrypto.getRandomValues(new Uint8Array(6)).toString(); // webcrypto
		const b = nodeCrypto.getRandomValues(new Uint8Array(6)).toString(); // namespace import
		const d = getRandomValues(new Uint8Array(6)).toString(); // named import
		return Response.json(results);
	},
};
```

Results in exceptions on these lines:

```ts
const b = nodeCrypto.getRandomValues(new Uint8Array(6)).toString(); // namespace import
const d = getRandomValues(new Uint8Array(6)).toString(); // named import
```

I could accept that the bare `getRandomValues()` call might not work. But I would expect the `nodeCrypto.getRandomValues()` call to work, which is the point of this issue.

**Comment by petebacondarwin** [comment]
Also given that this is for Node.js compatibility, I tested it on vanilla Node.js (18):

```
> const crypto = require("crypto")
undefined
> crypto.getRandomValues(new Uint8Array(6))
Uint8Array(6) [ 56, 123, 166, 65, 220, 221 ]
> crypto.getRandomValues(new Uint8Array(6))
> crypto.webcrypto.getRandomValues(new Uint8Array(6))
Uint8Array(6) [ 89, 169, 107, 187, 129, 83 ]
> const getRandomValues = crypto.getRandomValues
undefined
> getRandomValues(new Uint8Array(6))
Uint8Array(6) [ 82, 122, 19, 15, 222, 155 ]
```
