### ISSUE TITLE
🐛 Bug Report — Runtime APIs node:crypto 'Unrecognized or unimplemented EC curve "id-ecPublicKey" requested.'

### ISSUE THREAD

**Issue by 1yasa** [cloudflare/workerd#2768]
<img width="753" alt="image" src="https://github.com/user-attachments/assets/56d4e97c-4c25-46fc-bb25-7f7a7bad19e9">

`Unrecognized or unimplemented EC curve \"id-ecPublicKey\" requested` when use crypto with `compatibility_flags = ["nodejs_compat_v2"]` & wrangler v3.78.7.

Here is the error source:

https://github.com/agisboye/app-store-server-api/blob/main/src/Decoding.ts#L47

<img width="722" alt="截屏2024-09-19 21 16 03" src="https://github.com/user-attachments/assets/29d51933-3ed8-451c-ac42-1d96a212fd1d">

Here is the error detail:
<img width="1049" alt="截屏2024-09-19 21 17 04" src="https://github.com/user-attachments/assets/68e63f9f-6528-41d8-b2f9-7d59baef6042">

So my question is, the X509 implemented by workerd seems to be completely unusable when using the decodeJWS function of /app-store-server-api.

Did I make a mistake, or does the X509 implementation in workerd indeed throw an error when trying to get the public key with cert.publicKey? Below is my business code (for reproduction):

```ts
const app_store_api = getAppStoreApi()
const res_subscription = await app_store_api.getSubscriptionStatuses(tid!)

const item = res_subscription.data[0].lastTransactions.find(item => item.originalTransactionId === tid)!

const res_transaction = await decodeTransaction(item.signedTransactionInfo)
```

**Comment by 1yasa** [comment]
any progress？

**Comment by jasnell** [comment]
The runtime has a much more limited set of curves that it supports than Node.js and `id-ec-PublicKey` is not on that list. 

From: src/workerd/api/crypto/ec.c++ ...

```
EllipticCurveInfo lookupEllipticCurve(kj::StringPtr curveName) {
  static const std::map<kj::StringPtr, EllipticCurveInfo, CiLess> registeredCurves{
    {"P-256", {"P-256", NID_X9_62_prime256v1, 32}},
    {"P-384", {"P-384", NID_secp384r1, 48}},
    {"P-521", {"P-521", NID_secp521r1, 66}},
  };

  auto iter = registeredCurves.find(curveName);
  JSG_REQUIRE(iter != registeredCurves.end(), DOMNotSupportedError,
      "Unrecognized or unimplemented EC curve \"", curveName, "\" requested.");
  return iter->second;
}
```

The `node:crypto` implementation is still an active WIP so some functionality may still be limited or missing.

**Comment by 1yasa** [comment]
> The runtime has a much more limited set of curves that it supports than Node.js and `id-ec-PublicKey` is not on that list.
> 
> From: src/workerd/api/crypto/ec.c++ ...
> 
> ```
> EllipticCurveInfo lookupEllipticCurve(kj::StringPtr curveName) {
>   static const std::map<kj::StringPtr, EllipticCurveInfo, CiLess> registeredCurves{
>     {"P-256", {"P-256", NID_X9_62_prime256v1, 32}},
>     {"P-384", {"P-384", NID_secp384r1, 48}},
>     {"P-521", {"P-521", NID_secp521r1, 66}},
>   };
> 
>   auto iter = registeredCurves.find(curveName);
>   JSG_REQUIRE(iter != registeredCurves.end(), DOMNotSupportedError,
>       "Unrecognized or unimplemented EC curve \"", curveName, "\" requested.");
>   return iter->second;
> }
> ```
> 
> The `node:crypto` implementation is still an active WIP so some functionality may still be limited or missing.

Get.

**Comment by 1yasa** [comment]
any time support `id-ec-PublicKey`?

**Comment by aspirin2d** [comment]
[Apple App Store Server API](https://github.com/apple/app-store-server-library-node) needs this feature to verify it's signed objects.

**Comment by jasnell** [comment]
Marking as a feature request. Will investigate.

**Comment by oeed** [comment]
@1yasa I see you closed this issue, yet I'm still having the same issue. Is there a work around?

**Comment by 1yasa** [comment]
> I see you closed this issue, yet I'm still having the same issue. Is there a work around?

No, I commented out the relevant code and then executed the package

**Comment by oeed** [comment]
Could you please then reopen the issue so it can be fixed?

**Comment by 1yasa** [comment]
> Could you please then reopen the issue so it can be fixed?

But i review the relative pr，it's been done a few days ago. Maybe you should make a new issue for this after you confirm that.

**Comment by PiyushInfocusp** [comment]
Still facing the same, even after updating to 4.4.0
