### ISSUE TITLE
Breaking change in `res.arrayBuffer` types

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workerd#3186]
With the following code and the latest `4.20241127.0` version of `@cloudflare/workers-types`, this now produces a TypeScript error:

```ts
const response = await fetch('https://example.com');
const buffer = await response.arrayBuffer();
const bytes = new Uint8Array(buffer);
```

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'ArrayBuffer | ArrayBufferView' is not assignable to parameter of type 'ArrayBufferLike'.
      Type 'ArrayBufferView' is not assignable to type 'ArrayBufferLike'.
        Type 'ArrayBufferView' is missing the following properties from type 'SharedArrayBuffer': slice, [Symbol.species], [Symbol.toStringTag]
```

My real-world use-case is doing something like, which is needed to build attachments to send for emails, for example:
```ts
	const buffer = await res.arrayBuffer();
	const bytes = new Uint8Array(buffer);
	const base64Content = base64.stringify(bytes);
```

Reverting to `4.20241112.0` resolves this error.

---

Diff: https://npmdiff.dev/@cloudflare%2fworkers-types/4.20241112.0/4.20241127.0/package/experimental/index.ts
Raw diff: https://github.com/Cloudflare-Mining/Cloudflare-Datamining/commit/94385688551cbad84b7e32d2e36bdfce3f9d41c8

I suspect this is due to the change of the `arrayBuffer()` type on `Body` to now return `Promise<ArrayBuffer | ArrayBufferView>` vs the previous `Promise<ArrayBuffer>`

**Comment by emily-shen** [comment]
Hi, thanks for reporting this! we're aware of it and will be fixing asap 👍
