### ISSUE TITLE
🚀 Feature Request: Allow unsafe eval to run code in a separate I/O context

### ISSUE THREAD

**Issue by dario-piotrowicz** [cloudflare/workerd#3218]
In our [Vite plugin](https://github.com/flarelabs-net/vite-plugin-cloudflare), during development instead of normally importing modules, we use workerd's unsafe eval to evaluate and run their code.

This is so that we can integrate with the [Vite Environment API](https://vite.dev/guide/api-environment.html) and correctly integrate with Vite's dev modules handling (Vite doesn't work with real ESModules and has it's own custom modules structure, with that they can have more control over them, allow modules invalidations, etc...)

The issue here is that there might be differences between the evaluation of anonymous functions and actual ESModules importing, in particular we know that I/O operations can't be performed on the top level of a dynamically imported modules inside workerd.

This is problematic because this means that we end up with diverging behaviors during dev and production.

I am opening this issue to see if we could have some sort of API or any way to get unsafe eval to actually run code in the same manner as code run in imported modules, allowing us to cleanly reproduce the production during development as well.

For more context: https://github.com/flarelabs-net/vite-plugin-cloudflare/issues/83#issuecomment-2521343302

**Comment by jasnell** [comment]
Not "separate I/O context" but "no I/O context". The idea is that we do not want anything running in the unsafe eval to be able to schedule i/o.

**Comment by dario-piotrowicz** [comment]
> Not "separate I/O context" but "no I/O context". The idea is that we do not want anything running in the unsafe eval to be able to schedule i/o.

ah yes, thanks for the correction 🙂

**Comment by dario-piotrowicz** [comment]
PS: We had some further discussion about this and preventing I/O operations in `unstafe eval`ed code could actually not even work for us as we do rely on some global state anyways 😕 (for context: https://github.com/flarelabs-net/vite-plugin-cloudflare/issues/83#issuecomment-2532368321)

So this might actually not be a valid idea at all 😕

**Comment by dario-piotrowicz** [comment]
Closing this issue since, as we discussed in https://github.com/flarelabs-net/vite-plugin-cloudflare/issues/83 (https://github.com/flarelabs-net/vite-plugin-cloudflare/issues/83#issuecomment-2533132372) what I proposed here is something that wouldn't even really work for us, thanks and sorry for the inconvenience James 🙏
