### ISSUE TITLE
Requires `libc++-dev` for execution

### ISSUE THREAD

**Issue by helloimalastair** [cloudflare/workerd#33]
`libc++-dev` is listed as a build dependency in the README, but prebuilt `workerd` from npm will not execute without it installed.

Running Ubuntu Jammy Jellyfish.

**Comment by kentonv** [comment]
Technically it's `libc++1` that is required (which `libc++-dev` brings in as a dependency).

It's be nice if we could fold `libc++` and `libc++abi` into the Bazel build so that these don't have to be installed separately at all, and can be statically linked into the binary.

**Comment by kentonv** [comment]
https://github.com/cloudflare/workerd/issues/46#issuecomment-1263012389 discusses more things we should do to make our binaries more universally usable. Going to close this issue in favor of that.
