### ISSUE TITLE
Support peformance.now API

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workerd#390]
[`performance.now()`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) is a ubiquitous API that is supported by all popular JS runtimes except for `workerd`. The lack of support for this API hurts our interop and code portability.

I propose that we implement this API with similar limitations as Date.now() so that we don't open up a Spectre attack vector in `workerd` which is also in line with [privacy preserving precision reduction](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp#reduced_time_precision) implemented in browsers.

The simple polyfill that seems to work well for me for now looks like this:

```
globalThis.performance ||= {};
globalThis.performance.now ||= function now() {
	return Date.now();
};
```

**Comment by RichiCoder1** [comment]
I'm currently maintaining a rather ugly patch in my lib that I'd love to delete via this: https://github.com/RichiCoder1/opentelemetry-sdk-workers/blob/main/packages/opentelemetry-sdk-workers/src/performance.ts

**Comment by geelen** [comment]
Any progress on this? I've started using `const performance = globaThis.performance || Date` but I certainly think we should let people access high-resolution timers if they want to, maybe with a compatibility flag?

**Comment by geelen** [comment]
Oh right, I was doing something dumb, this looks like it's been added in https://github.com/cloudflare/workerd/pull/603

@IgorMinar is that everything you wanted? Care to close this issue if so?

**Comment by jasnell** [comment]
`performance.now` is supported with the same precision as `Date.now`. For local testing, we might consider allowing an option where `performance.now` yields full precision when running in workerd.

**Comment by IgorMinar** [comment]
yes! This indeed seems to be resolved now. Closing. Thank you!
