### ISSUE TITLE
`EmailMessage` has an unused type parameter

### ISSUE THREAD

**Issue by BeeeQueue** [cloudflare/workerd#395]
https://github.com/cloudflare/workerd/blob/77d9e82/types/defines/email.d.ts#L4
```ts
interface EmailMessage<Body = unknown> {
                    // ^ Body is declared but never used
```

This type parameter is declared but never used, leading to type errors if `noUnusedParameters` is enabled.

The exact problem seems to be that there's a `index.ts` file in the package that gets type checked for whatever reason

**Comment by jakejosephcs** [comment]
+1 to this. Experiencing the same issue
