### ISSUE TITLE
nodejs_compat flag causes error during Pages build

### ISSUE THREAD

**Issue by AaronFriel** [cloudflare/workerd#403]
This flag is needed to enable Next.js on Pages with Node 16, see: https://github.com/cloudflare/next-on-pages/issues/79

Using Workers runtime version 2023-02-27, Pages builds with this flag set result in an error: 

> 16:46:07.894 Error: Failed to publish your Function. Got error: The compatibility flag nodejs_compat is experimental and cannot yet be used in Workers deployed to Cloudflare.

**Comment by jasnell** [comment]
We are still about a week away from the `nodejs_compat` flag being fully pulled out from behind experimental status which will enable the use of the `AsyncLocalStorage` API needed by next.js.

**Comment by AaronFriel** [comment]
Ah, unfortunate timing for my use of the next-on-pages docs then.

**Comment by KianNH** [comment]
This flag is live now, fyi.

**Comment by AaronFriel** [comment]
Thank you!

**Comment by syonfox** [comment]
Did I do something wrong I tried using this flag in pages no framework and the server would not accept it just the other day. I put nodejs_compat as a "tag" in the UI for many pages under pages->page->settings->function 

this caused the build to fail

**Comment by irvinebroque** [comment]
@syonfox — can you review the docs [here](https://developers.cloudflare.com/workers/runtime-apis/nodejs/) and post what specifically failed?

**Comment by syonfox** [comment]
Here is the details, a also tried the node:xyz import but it appears to be failing before




<pre class="c_jq c_bu c_iq c_ir c_nf c_ng c_de c_nu c_nv c_nw c_nx c_fo c_fp c_nh c_bw c_ny">

15:02:08.904 | Found Functions directory at /functions. Uploading.
-- | --
15:02:09.745 | ✘ [ERROR] 3 error(s) and 0 warning(s) when compiling Worker.
15:02:09.746 |  
15:02:09.747 |  
15:02:09.749 |  
15:02:09.751 | ✘ [ERROR] Could not resolve "async_hooks"
15:02:09.752 |  
15:02:09.752 | nodeTest.js:3:49:
15:02:09.752 | 3 │ import { AsyncLocalStorage, AsyncResource } from 'async_hooks';
15:02:09.752 | ╵                                                  ~~~~~~~~~~~~~
15:02:09.752 |  
15:02:09.752 | The package "async_hooks" wasn't found on the file system but is built into node.
15:02:09.752 | Add "node_compat = true" to your wrangler.toml file to enable Node compatibility.
15:02:09.752 |  
15:02:09.753 |  
15:02:09.753 | ✘ [ERROR] Could not resolve "buffer"
15:02:09.753 |  
15:02:09.753 | nodeTest.js:4:23:
15:02:09.753 | 4 │ import { Buffer } from 'buffer';
15:02:09.753 | ╵                        ~~~~~~~~
15:02:09.753 |  
15:02:09.753 | The package "buffer" wasn't found on the file system but is built into node.
15:02:09.754 | Add "node_compat = true" to your wrangler.toml file to enable Node compatibility.
15:02:09.754 |  
15:02:09.754 |  
15:02:09.754 | ✘ [ERROR] Could not resolve "events"
15:02:09.754 |  
15:02:09.754 | nodeTest.js:5:29:
15:02:09.754 | 5 │ import { EventEmitter } from 'events';
15:02:09.754 | ╵                              ~~~~~~~~
15:02:09.755 |  
15:02:09.755 | The package "events" wasn't found on the file system but is built into node.
15:02:09.755 | Add "node_compat = true" to your wrangler.toml file to enable Node compatibility.
15:02:09.755 |  
15:02:09.755 |  
15:02:09.755 | ✘ [ERROR] Build failed with 3 errors:
15:02:09.755 |  
15:02:09.755 | nodeTest.js:3:49: ERROR: Could not resolve "async_hooks"
15:02:09.756 | nodeTest.js:4:23: ERROR: Could not resolve "buffer"
15:02:09.756 | nodeTest.js:5:29: ERROR: Could not resolve "events"
15:02:09.756 |  
15:02:09.756 |  
15:02:09.767 | Failed building Pages Functions.
15:02:10.690 | Failed: an internal error occurred

</pre>

![image](https://user-images.githubusercontent.com/9345677/229241107-ca0061c1-075b-47b6-b3a2-5530d8fdc782.png)

![image](https://user-images.githubusercontent.com/9345677/229241194-e35f4a66-c2b6-43dd-a6a7-6697daea288a.png)


```
import { AsyncLocalStorage, AsyncResource } from 'async_hooks';
import { Buffer } from 'buffer';
import { EventEmitter } from 'events';
    // assert(true)
    let ls = new AsyncLocalStorage()
    let b = new Buffer()
    let e = new EventEmitter()
    // util
export async function onRequest(request) {
    // const question = getRandomQuestion()
    let kv = request.env.kv;

    let myKey = 'kvCount'
    let oldN = await kv.get(myKey, {type: "json"}); // Possible types are "text", "arrayBuffer", "json", and "stream".
    oldN++;
    let html = "Count is: " + oldN;

    kv.put(myKey, oldN);

    const response = new Response(html, {
        headers: {'Content-Type': 'text/html'},
    })


    return response
}
```

**Comment by KianNH** [comment]
Prefix them with `node:`, like `import { foo } from node:async_hooks`

**Comment by syonfox** [comment]
Same results note i have also tried putting 
```
node_compat = true

```
in a `wrangler.toml` file in both the repo root and the functions directory

But it seems to not be getting enabled

<pre class="c_jh c_bu c_ik c_il c_si c_sj c_de c_px c_sv c_sw c_sx c_fo c_fp c_sk c_bw c_sy">

15:27:38.014 | Wrote _routes.json exluding public files explicitly count:  11
-- | --
15:27:38.014 | Page index generated successfully:  public/index.html
15:27:38.034 | Finished
15:27:38.035 | Found Functions directory at /functions. Uploading.
15:27:38.901 | ✘ [ERROR] 3 error(s) and 0 warning(s) when compiling Worker.
15:27:38.902 |  
15:27:38.902 |  
15:27:38.905 |  
15:27:38.908 | ✘ [ERROR] Could not resolve "node:async_hooks"
15:27:38.908 |  
15:27:38.908 | nodeTest.js:3:49:
15:27:38.908 | 3 │ import { AsyncLocalStorage, AsyncResource } from 'node:async_hooks';
15:27:38.908 | ╵                                                  ~~~~~~~~~~~~~~~~~~
15:27:38.909 |  
15:27:38.909 | The package "node:async_hooks" wasn't found on the file system but is built into node.
15:27:38.909 | Add "node_compat = true" to your wrangler.toml file to enable Node compatibility.
15:27:38.909 |  
15:27:38.909 |  
15:27:38.909 | ✘ [ERROR] Could not resolve "node:buffer"
15:27:38.909 |  
15:27:38.909 | nodeTest.js:4:23:
15:27:38.909 | 4 │ import { Buffer } from 'node:buffer';
15:27:38.910 | ╵                        ~~~~~~~~~~~~~
15:27:38.910 |  
15:27:38.910 | The package "node:buffer" wasn't found on the file system but is built into node.
15:27:38.910 | Add "node_compat = true" to your wrangler.toml file to enable Node compatibility.
15:27:38.910 |  
15:27:38.910 |  
15:27:38.910 | ✘ [ERROR] Could not resolve "node:events"
15:27:38.910 |  
15:27:38.911 | nodeTest.js:5:29:
15:27:38.911 | 5 │ import { EventEmitter } from 'node:events';
15:27:38.911 | ╵                              ~~~~~~~~~~~~~
15:27:38.911 |  
15:27:38.911 | The package "node:events" wasn't found on the file system but is built into node.
15:27:38.911 | Add "node_compat = true" to your wrangler.toml file to enable Node compatibility.
15:27:38.911 |  
15:27:38.911 |  
15:27:38.912 | ✘ [ERROR] Build failed with 3 errors:
15:27:38.912 |  
15:27:38.912 | nodeTest.js:3:49: ERROR: Could not resolve "node:async_hooks"
15:27:38.912 | nodeTest.js:4:23: ERROR: Could not resolve "node:buffer"
15:27:38.912 | nodeTest.js:5:29: ERROR: Could not resolve "node:events"
15:27:38.912 |  
15:27:38.912 |  
15:27:38.925 | Failed building Pages Functions.
15:27:40.061 | Failed: an internal error occurred

</pre>

**Comment by KianNH** [comment]
`node_compat = true` are old polyfills that isn't relevant to the `nodejs_compat` compatibility flag - which one are you using in that log?

**Comment by syonfox** [comment]
It was node_compat , I'll try the other way,  if you don't mide where is the correct location in a page's project for the wrangler.toml

- asset root
- functions dire
- project root
- or repo root?

**Comment by KianNH** [comment]
Nowhere - Pages doesn't use a `wrangler.toml`, all configuration is done in the dashboard.

**Comment by syonfox** [comment]
Thats what I thought, and is there any special way to enter it into the input see screenshot above,  I tried adding both node_compat and nodejs_compat but still not working. 

do you need to enter the full line ie `nodejs_compat=true` as the 'tag'

**Comment by syonfox** [comment]
I just made a brand new blank and empty project for a minimal example.

It still appears to not work.

Let me know if there's anything you see that's off thanks for your help. this is all the information I have. 

https://user-images.githubusercontent.com/9345677/229248329-24426137-2e1a-4424-80cb-1706b6ea1ea3.mp4

**Comment by irvinebroque** [comment]
Thanks @syonfox — can reproduce what you're seeing with a starter project. Looks like you're doing the right thing. Escalating internally so that we address this, will follow up here.

**Comment by PoisnFang** [comment]
@irvinebroque Any update? I ma still having this issue

**Comment by Edweis** [comment]
I still have the issue as well

**Comment by syonfox** [comment]
Also, does anyone know if there is a working compatibility date for nodejs_compat?

**Comment by junilm** [comment]
I am having the same issue, anyone know anyway to solve this?

**Comment by syonfox** [comment]
Yeah looking to get my pages pipeline setup and it's important to have
nodejs support in the pages function

One should have access to native node libraries like Buffer etc
be able to use node_modules with require syntax rather than being forced to
copy all files into the functions folder.

This allows a vanilla project to be built directly on top of pages with
little development overhead.

For example, if we want to build a blog that has some functions doing extra
functionality we can deploy some npm packages and wite api specific
workers. in our project, we would just

```js
//npm install my-pakage
///functions/my-api.js
let myObj = require("my-pakage)
export default function onRequest(ctx) {
   //setup response and stream back start
   myObj.expensivePromise().then(ret=>{
      myResponse.addData(ret) // pseudo code
   })
}
```

And other fun stuff.

I get that this is possible by complex build chains but it would be nice to
keep this vanilla and compatible with running logic on both node servers
and cloudflare


Thanks, ... Humanity has the shared goal of life.
Kier Lindsay

[image: Join Endpoint] <https://join.endpoint.ca>
W: endpoint.ca
P: kierlindsay.ca

**Comment by robclancy** [comment]
> Thanks @syonfox — can reproduce what you're seeing with a starter project. Looks like you're doing the right thing. Escalating internally so that we address this, will follow up here.

Holy fuck did you delete the issue instead of escalate? This feature literally doesn't work. For 6 months.

I'm migrating a project and now realize it's a complete waste of time and that I'll have to go to another service.

**Comment by syonfox** [comment]
Well just for some documentation sharing on Cloudflare 

this is what I scraped out of the environment in prod. so this is probably a save starting point, not this is before request time so some stuff can't be used 

Hope this helps someone also https://developers.cloudflare.com/workers/runtime-apis/

```
[
    // Global variables and objects
    "global",
    "self",
    "console",
    "navigator", // Used primarily to obtain user agent information.
    
    // Data retrieval and asynchronous operations
    "fetch", // Allows data retrieval within a function.
    "setTimeout", // Note that this can only be executed in the request context, and most other operations are restricted.
    "setInterval", // Typical JavaScript functionality.
    "clearInterval",
    "clearTimeout",
    
    // Fundamental JavaScript objects
    "Object",
    "Array",
    "JSON",
    "Promise",
    "Map",
    "Set",
    "Math",
    "RegExp",
    "Date",
    "Error",
    
    // Module importing (e.g., CommonJS)
    "require", // This is used for importing modules, and it is expected to work with the 'node_modules' directory. Q: How do you typically validate the correctness of imports?
    
    // Performance-related information
    "performance", // This provides performance-related information. However, there are security restrictions that prevent benchmarking requests outside specific tooling environments. You may need to work within these limitations or find creative solutions.
    
    // Form data handling
    "FormData", // Used for handling form data.
    
    // WebSocket functionality
    "WebSocket" // WebSocket functionality is particularly useful for real-time communication. Consider exploring its potential, such as with tools like gun.eco.
]

```


@irvinebroque do you know if there a nicer efficient list of runtime APIs available depending on compatibility date, maybe a hit to where it is in code if nothing else?

... there is probably a way of scraping Wrangler for it by running with different dates. 
... another idea is to use the way back machine on the URL
... really it would be nice to have a blog post or documentation page written about something like that for people trying to bootstrap different environments.  

PS Thanks for the cool infrastructure can definitely simplify some things in the dev process.

**Comment by syonfox** [comment]
https://developers.cloudflare.com/workers/configuration/compatibility-dates/
