### ISSUE TITLE
streams_enable_constructors not documented

### ISSUE THREAD

**Issue by guest271314** [cloudflare/workerd#419]
```
async function handle(request) {
  return new Response(new ReadableStream({
    start(c) {c.enqueue(new Uint8Array([1,2,3])); c.close()}
  }), responseInit);
}
```
```
./workerd-linux-64 serve config.capnp
workerd/server/server.c++:2225: 
error: Uncaught exception:
 workerd/jsg/_virtual_includes/jsg/workerd/jsg/value.h:1347: 
failed: remote.jsg.Error: 
To use the new ReadableStream() constructor, enable the streams_enable_constructors feature flag.
stack: ./workerd-linux-64@1948b90 
./workerd-linux-64@1949759 
./workerd-linux-64@1814c10 
./workerd-linux-64@1815240 
./workerd-linux-64@1816080 
./workerd-linux-64@18166a0 
./workerd-linux-64@1d11790 ./workerd-linux-64@1d142a0
```
I searched this repository for `streams_enable_constructors`, = zero (0) results were yielded.

**Comment by KianNH** [comment]
From #391 

https://github.com/cloudflare/workerd/blob/1b5057f2bfcfedf146f6f79ff04e99903d55412b/src/workerd/io/compatibility-date.capnp#L114-L120

https://developers.cloudflare.com/workers/platform/compatibility-dates/

Check that your compatibility date is on or after the default date, or add it to your capnp config.

https://github.com/cloudflare/workerd/blob/1b5057f2bfcfedf146f6f79ff04e99903d55412b/src/workerd/server/workerd.capnp#L250-L256

**Comment by guest271314** [comment]
So what do I do? Copy this


https://github.com/cloudflare/workerd/blob/1b5057f2bfcfedf146f6f79ff04e99903d55412b/src/workerd/io/compatibility-date.capnp#L114-L120


 
to configuration file?

**Comment by guest271314** [comment]
I'm just testng helloworld example. That configuration file format is insane. Never seen anything like it. JSON is far more user friendly. I have no idea what to do with the content in the links you posted. I tried copying them to the configuration file in helloworld. Errors are still thrown.

**Comment by guest271314** [comment]
I tried this

```
const helloWorld :Workerd.Worker = (
  serviceWorkerScript = embed "worker.js",
  compatibilityDate = "2023-02-28",
  streams_enable_constructors = true
);
```

```
 ./workerd-linux-64 serve config.capnp
config.capnp:34:3-30: Struct has no field named 'streams_enable_constructors'.
```

**Comment by guest271314** [comment]
I ran the streams enabled with

```
const helloWorld :Workerd.Worker = (
  serviceWorkerScript = embed "worker.js",
  compatibilityDate = "2023-02-28",
  # streams_enable_constructors = true
);
```

However, workerd streams don't work.

A stream to respond with

```
async function handle(request) {
  let n = 0;
  return new Response(new ReadableStream({
    start(c) {
      // c.enqueue(new Uint8Array([1,2,3])); c.close()
    },
    async pull(c) {
      for (let n = 0; n < 255; i++) {
        c.enqueue(new Uint8Array([n])); 
        await new Promise((r) => setTimeout(r, 1000));
      }
      c.close();
    }
  }), responseInit);
}
```

On Chromium 113 at DevTools `console` I run

```
r = await fetch('http://localhost:8080');
r.body.pipeTo(new WritableStream({
  write(v) {
    console.log(v);
  }, close() {
    console.log('closed');
  }
})).catch(console.error);
```

Only the first `Uint8Array` is printed to `console` and then `'closed'` is printed

```
VM712:4 Uint8Array [0, buffer: ArrayBuffer(1), ...]
VM712:6 closed
```

at terminal we still get errors (formatted for this post)

```
$ ./workerd-linux-64 serve config.capnp
workerd/server/server.c++:2225: 
error: Uncaught exception: workerd/jsg/_virtual_includes/jsg/workerd/jsg/value.h:1347: 
failed: remote.jsg.ReferenceError: i is not defined
stack: ./workerd-linux-64@18c71c0 
./workerd-linux-64@1948b90 
./workerd-linux-64@1949759 
./workerd-linux-64@1814c10 
./workerd-linux-64@1815240 
./workerd-linux-64@1816080 
./workerd-linux-64@18166a0 
./workerd-linux-64@1d11790 
./workerd-linux-64@1d142a0
workerd/server/server.c++:2225: 
error: Uncaught exception: workerd/jsg/_virtual_includes/jsg/workerd/jsg/value.h:1347: failed: remote.jsg.ReferenceError: i is not defined
stack: ./workerd-linux-64@18c71c0 
./workerd-linux-64@1948b90 
./workerd-linux-64@1949759 
./workerd-linux-64@1814c10 
./workerd-linux-64@1815240
./workerd-linux-64@1816080 
./workerd-linux-64@18166a0 
./workerd-linux-64@1d11790 
./workerd-linux-64@1d142a0
```

**Comment by KianNH** [comment]
> `failed: remote.jsg.ReferenceError: i is not defined`

This isn't related to streams, you're just using the wrong variable name in your loop.

```diff
- for (let n = 0; n < 255; i++)
+ for (let n = 0; n < 255; n++)
```

**Comment by guest271314** [comment]
That explains it. Got it working. 

The ".capnp" configuration format is **_unecessarily_** complicated. It's an entire language in and of itself. JSON will suffice.

It sure would be helpful to post the instruction to enable streams in the README. That is what this issue is about.

**Comment by guest271314** [comment]
Preferably no configuration file is necessary at all. That is why I started using `deno` executable, to get away from package.json and `node_modules` and `npm`.

**Comment by kentonv** [comment]
Since this is the second time this flag has come up, perhaps the action items for us are:

1. Update our examples to use the latest compat date, to ensure people copy/pasting the examples get the latest and greatest.
2. Maybe update the error message to include a link to the documentation on compat dates/flags.

**Comment by guest271314** [comment]
> 1. Update our examples to use the latest compat date, to ensure people copy/pasting the examples get the latest and greatest.

Since your configuration file is critical to your application you should have already been doing that.

The fact that you have failed to do that means the process is too tedious. Just use something like "latest", like other builds do.

The date thing is a bad idea. [The Mystery behind January 1st, 1753](https://www.linkedin.com/pulse/mystery-behind-january-1st-1753-syed-imad-husain). This is how I fetch Node.js nightly release 

```
let [node_nightly_build] = await (
            await fetch('https://nodejs.org/download/nightly/index.json')
          ).json();
          let { version, files } = node_nightly_build;
          let node_nightly_url = `https://nodejs.org/download/nightly/${version}/node-${version}-${osArch}.tar.gz`;
```

There is a date filed in the JSON, however all I have to do is decontruct the latest entry.

What happens when you have millions of users, and are updating daily, like Chromium Dev Channel? You will literally have to update you samples and configuration files every day. Why make a chore for yourself - and others?

The configuration file _can be_ **far** simpler. Just use JSON if you insist on using a configuration file to control your application. I began using Deno to get away from package.json in Node.js, then figured out how to use `node` executable without package.json, node_modules, or carrying around npm.

**Comment by KianNH** [comment]
You seem to be confusing the compatibility date for the overall 'version' of a release. Compatibility dates are a concept where breaking changes are gated behind a flag that has a default-on date - meaning that if I make a breaking change tomorrow, it won't impact your Worker that has a compatibility date of `2022-03-07`.

https://blog.cloudflare.com/backwards-compatibility-in-cloudflare-workers/

A compatibility date of `latest` goes against the spirit of how backwards compatibility is handled in Workers. The reason that `streams_enable_constructors` is required is because originally, the Streams API classes didn't have constructors - and now they do. Since this is a change in behaviour, it is behind a compatibility date/flag.

If you want to fetch the latest release of `workerd`, you can do the same as what you're doing for Node. Fetch the releases (https://api.github.com/repos/cloudflare/workerd/releases) and then download the latest asset for your architecture.

**Comment by guest271314** [comment]
> You seem to be confusing the compatibility date for the overall 'version' of a release. Compatibility dates are a concept where breaking changes are gated behind a flag that has a default-on date - meaning that if I make a breaking change tomorrow, it won't impact your Worker that has a compatibility date of 2022-03-07.

No.

I'm saying you folks couldn't even keep up with your own _unnecessarily complicated_ configuration file in your samples directory. 

Just use JSON and _something like_ "latest" if you want to do something different that "what the other cool kids" are doing.

> A compatibility date of latest goes against the spirit of how backwards compatibility is handled in Workers. The reason that streams_enable_constructors is required is because originally, the Streams API classes didn't have constructors - and now they do. Since this is a change in behaviour, it is behind a compatibility date/flag.

Right, but you folks never bothered to update your own samples to reflect that  in your own _samples_. That means it is too tedious to update even for maintainers.

> If you want to fetch the latest release of workerd, you can do the same as what you're doing for Node. Fetch the releases (https://api.github.com/repos/cloudflare/workerd/releases) and then download the latest asset for your architecture.

Good to know. All of this should be in your README. _Knowingly_ withholding critical information from folks who might just happen to check out your gear is not helpful. Might as well just make the repository private if you are not going to explain what is going on from the perspective you want users to know what is going on.

That configuration file format is an entire language in an of itself. Just use JSON. I get it. C++ is verbose. That doesn't mean you have to stck with a system that you can't even keep up with - and refuse to update your README when a user says, "Hey, why aren't streams working?". Oh, the maintainers neglected to update their samples with _dates_. Why place that chore on yourself?
