### ISSUE TITLE
CPU/Memory limits

### ISSUE THREAD

**Issue by apkumar** [cloudflare/workerd#49]
Is there a way to configure CPU or memory limits for workers? I don't see anything related in workerd.capnp; in the code, I see the IsolateLimitEnforcer interface, but no non-null implementations.

**Comment by jasnell** [comment]
There is currently no way to configure the limits and no implementation in workerd currently. I don't believe we are currently planning on implementing limits here any time soon but it's something we can discuss

**Comment by kentonv** [comment]
Hi @apkumar,

Yes, sorry, there are a couple reasons the code we use for limit enforcement in Cloudflare Workers isn't included here:

1. It's very platform-specific, relying on non-portable Linux kernel features. We wanted `workerd` to port nicely to Mac and other platforms.
2. As mentioned in the readme and blog post, `workerd` is not appropriate as a sandbox for running code you don't trust. Limiting resources seems like a feature that's only necessary when running code you don't trust -- but if you are doing that with `workerd`, you need to be wrapping it in another sandboxing layer anyway. Most such sandboxing layers can already enforce resources limits on their own. So, we think it's best to rely on them instead.

At this time we do not plan to provide resource limiting as part of workerd, though it's always possible we'll revisit this in the future.
