### ISSUE TITLE
Feature Request — change-array-by-copy APIs

### ISSUE THREAD

**Issue by Cherry** [cloudflare/workerd#517]
It would be great to get these APIs landed in Workers:

`Array.prototype.toReversed() -> Array`
`Array.prototype.toSorted(compareFn) -> Array`
`Array.prototype.toSpliced(start, deleteCount, ...items) -> Array`
`Array.prototype.with(index, value) -> Array`

They have just started shipping with Chrome 110, so I expect we're going to see them show up more and more over the near future.

More details: https://github.com/tc39/proposal-change-array-by-copy
V8 implementation: https://bugs.chromium.org/p/v8/issues/detail?id=12764

**Comment by kentonv** [comment]
We shipped V8 11.0 in late February, so these should have landed then, and AFAICT they are indeed supported today. Are you finding they are missing somewhere?

**Comment by jasnell** [comment]
Node.js 20.0.0 will be releasing later this month with v8 11.3 and will have these.
