### ISSUE TITLE
🐛 Bug Report — Runtime APIs: console throws with frozen global scope

### ISSUE THREAD

**Issue by marcusdarmstrong** [cloudflare/workerd#527]
`workerd` @ `v1.20230404.0`:

A straightforward worker configuration:
```
addEventListener("fetch", event => {
  Object.freeze(self);
  console.log("test");
  event.respondWith(
    new Response("Hello World")
  );
});
```

Succeeds for the first request, but subsequent requests throw with:
```
workerd  | workerd/server/server.c++:2229: error: Uncaught exception: workerd/jsg/_virtual_includes/jsg/workerd/jsg/value.h:1347: failed: remote.jsg.Error: Failed to get the 'origin' property on 'ServiceWorkerGlobalScope': the property is not implemented.
```

**Comment by A-N-uraag** [comment]
Hi @marcusdarmstrong , I tried to reproduce this bug on the current `main` branch build. Looks like this is not an issue anymore. Can you confirm?

**Comment by marcusdarmstrong** [comment]
Hi, yes, I'm no longer able to reproduce this issue since updating to the 2023-05-18 release.
