### ISSUE TITLE
🐛 Bug Report — Runtime APIs: "Called .text() on an HTTP body" detection false-positives

### ISSUE THREAD

**Issue by hmnd** [cloudflare/workerd#528]
An API I'm querying in a worker has the `Content-Type` in its responses set to `application/json; charset="utf-8"`. This results in the following message being incorrectly displayed in my console every time I make a request to the API:

`Called .text() on an HTTP body which does not appear to be text. The body's Content-Type is "application/json; charset="utf-8"". The result will probably be corrupted. Consider checking the Content-Type header before interpreting entities as text.`

It seems the code [here](https://github.com/cloudflare/workerd/blob/685f647d98e1735ae1be3196c365bee50c834c54/src/workerd/api/http.c%2B%2B#L654-L666) and [here](https://github.com/cloudflare/workerd/blob/685f647d98e1735ae1be3196c365bee50c834c54/src/workerd/api/r2-bucket.c%2B%2B#L926-L938) only checks that `Content-Type` does not end in exactly `charset=UTF-8`  or `charset=utf-8`. I believe it should instead split the value by `;`, to ensure that only the 'type' part of the header is checked against not ending in xml/json/javascript.

You can use this worker to repro:
```javascript
export default {
  async fetch(request, env) {
    const testResp = new Response(JSON.stringify({}), {
      headers: {
        'content-type': 'application/json; charset="utf-8"'
      }
    });

    await testResp.json();

    return new Response();
  }
}
```

**Comment by jasnell** [comment]
Yeah that checking logic is a bit unfortunate. I think ideally we should have proper MIME type parsing and handling there rather than relying on naive text parsing, and we shouldn't have this logic duplicated in two different spots.

**Comment by jihuayu** [comment]
Hi, I want to do it.
We can use `readContentTypeParameter` to get `charset`, and use `contentType.findFirst(';')` to get `MimeType`. Am I right.
I think we can create a new function named `warnIfOnNonTextContent` for this code. Should I put this function in `util.h` file?
```c++
    KJ_IF_MAYBE(type, KJ_REQUIRE_NONNULL(httpMetadata).contentType) {
      if (!type->startsWith("text/") &&
          !type->endsWith("charset=UTF-8") &&
          !type->endsWith("charset=utf-8") &&
          !type->endsWith("xml") &&
          !type->endsWith("json") &&
          !type->endsWith("javascript")) {
        context.logWarning(kj::str(
            "Called .text() on an HTTP body which does not appear to be text. The body's "
            "Content-Type is \"", *type, "\". The result will probably be corrupted. Consider "
            "checking the Content-Type header before interpreting entities as text."));
      }
    }
```

**Comment by jasnell** [comment]
I've introduced a new proper MimeType parser in `src/workerd/util/mimetype.h` and I consolidated the two places where this warning is emitted into a single utility function. The next step would be to just replace the current if block there with the new `workerd::MimeType`.
