### ISSUE TITLE
URL.toString works inconsistently

### ISSUE THREAD

**Issue by oxcafedead** [cloudflare/workerd#538]
Hi!

Recently I found a strange behavior with my worker.

This is different from Chrome/Firefox/Node.js and looking at spec, seems like the spec describes a different behavior.

https://github.com/cloudflare/workerd/blob/17a927f2f98e5115c643729725076b00f0e7d3b1/src/workerd/api/url-standard.c%2B%2B#L2081

The parameters are percent-encoded during the `toString` invocation.

So, if we evaluate:
```javascript
new URL("https://mytest.workers.dev/?h=e3Rlc3QhfQ==").toString()
```
Chrome/Firefox/Node.js output:
`https://mytest.workers.dev/?h=e3Rlc3QhfQ==`
Workerd output:
`https://mytest.workers.dev/?h=e3Rlc3QhfQ%3D%3D`

I know, from rfc3986 angle it all makes sense. However, the spec which describes `toString` behavior does not tell to percent-encode parameters, if I'm not mistaken:
* https://url.spec.whatwg.org/#dom-url-href
* https://url.spec.whatwg.org/#url-serializing

Can this be changed somehow? Maybe some additional flag?

**Comment by jasnell** [comment]
What is your compatibility date? Make sure that you're compatibility date is 2022-10-31 or later or that you have the `url_standard` compatibility flag enabled to use the standardized URL implementation (https://developers.cloudflare.com/workers/platform/compatibility-dates/#new-url-parser-implementation).

Also, FWIW, Node.js' implementation of URL is more standards compliant than either Chrome or Firefox's so be sure to use that as the baseline.

**Comment by oxcafedead** [comment]
@jasnell you are right, the compatibility date was 2022-10-21 😄 

So, seems like there is already such possibility.

Thanks! Closing as stale...
