### ISSUE TITLE
FAILED: Build did NOT complete successfully - workerd Ubuntu 22.04.01 x86-64 

### ISSUE THREAD

**Issue by meseguera** [cloudflare/workerd#57]
1664488957.661890805: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /sys/fs/cgroup
1664488957.661898383: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /sys/fs/pstore
1664488957.661905646: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /sys/fs/bpf
1664488957.661911495: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /sys/kernel/debug
1664488957.661916752: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /sys/kernel/tracing
1664488957.661921753: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /sys/kernel/config
1664488957.661926458: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /sys/fs/fuse/connections
1664488957.661932116: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /proc
1664488957.661936706: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /proc/sys/fs/binfmt_misc
1664488957.661943104: src/main/tools/linux-sandbox-pid1.cc:391: remount(nullptr, /proc/sys/fs/binfmt_misc, nullptr, 2101281, nullptr) failure (Operation not permitted) ignored
1664488957.661948677: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /proc/sys/fs/binfmt_misc
1664488957.661953427: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /snap/core20/1518
1664488957.661958087: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /snap/lxd/22923
1664488957.661962319: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /snap/snapd/16292
1664488957.661978338: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /boot/efi
1664488957.661982909: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /snap/snapd/17029
1664488957.661986858: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /snap/core20/1623
1664488957.661990698: src/main/tools/linux-sandbox-pid1.cc:371: remount ro: /snap/lxd/23541
1664488957.661995210: src/main/tools/linux-sandbox-pid1.cc:371: remount rw: /root/.cache/bazel/_bazel_root/e9082452e993cc03c3ef8055d948726b/sandbox/linux-sandbox/1/execroot/workerd
1664488957.662000220: src/main/tools/linux-sandbox-pid1.cc:371: remount rw: /root/.cache/bazel/_bazel_root/e9082452e993cc03c3ef8055d948726b/sandbox/linux-sandbox/1/execroot/workerd
1664488957.662011398: src/main/tools/linux-sandbox-pid1.cc:371: remount rw: /tmp
1664488957.662015858: src/main/tools/linux-sandbox-pid1.cc:371: remount rw: /dev/shm
1664488957.662060759: src/main/tools/linux-sandbox-pid1.cc:460: calling fork...
1664488957.662174897: src/main/tools/linux-sandbox-pid1.cc:490: child started with PID 2
bazel-out/k8-opt-exec-2B5CBBC6/bin/external/capnp-cpp/src/capnp/capnpc-c++: plugin failed: Killed
1664488959.589073935: src/main/tools/linux-sandbox-pid1.cc:507: wait returned pid=2, status=0x100
1664488959.589088742: src/main/tools/linux-sandbox-pid1.cc:525: child exited normally with code 1
1664488959.589825799: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
Target //src/workerd/server:workerd failed to build
INFO: Elapsed time: 36.602s, Critical Path: 2.03s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

**Comment by meseguera** [comment]
#57 OS
Static hostname: ubuntu-s-1vcpu-1gb-nyc1-01
       Icon name: computer-vm
         Chassis: vm
      Machine ID: 10ac445ef7ec4e34c52206426335fee2
         Boot ID: da5ca6972a2142b9b8570e30de5cd325
  Virtualization: kvm
Operating System: Ubuntu 22.04.1 LTS              
          Kernel: Linux 5.15.0-48-generic
    Architecture: x86-64
 Hardware Vendor: DigitalOcean
  Hardware Model: Droplet

**Comment by kentonv** [comment]
I think most likely what happened here is your machine doesn't have enough RAM to run the workerd build. It looks like a random build step was killed, which is often indicative of Linux's OOM (out-of-memory) killer kicking in. It looks like the VM you were using has only 1GB of RAM, which is pretty low. I think we have individual compile steps where the compiler typically goes over 1GB. So probably you need to use a machine with more RAM. (More cores would help the build go faster, too.)

**Comment by meseguera** [comment]
Thanks Kentonv... will do
