### ISSUE TITLE
The Binary in npm package is not executable 

### ISSUE THREAD

**Issue by Mbiakop1** [cloudflare/workerd#61]
And I think can be solved by performing this ` To use this, supply a bin field in your package.json which is a map of command name to local file name. On install, npm will symlink that file into prefix/bin for global installs, or ./node_modules/.bin/ for local installs.`

For example, myapp could have this:

```{ "bin" : { "myapp" : "./cli.js" } }```

So, when you install myapp, it’ll create a symlink from the cli.js script to /usr/local/bin/myapp.

**Comment by kentonv** [comment]
Hmm it seems like a lot of people have been able to run it... could something be different about your environment?

**Comment by penalosa** [comment]
We do have that field in the npm package-could you share the command you're trying to run that's failing?

**Comment by Mbiakop1** [comment]
> Hmm it seems like a lot of people have been able to run it... could something be different about your environment?

Okey! may be that should be the case

**Comment by penalosa** [comment]
Closing this for now, because it doesn't seem to be a widespread problem. If you're still running into issues and have more details about your specific environment, we can re-open.
