### ISSUE TITLE
🐛 Bug Report — Runtime APIs: Socket API Inoperable in WebSocket Context with Silent Failures

### ISSUE THREAD

**Issue by xiaokangwang** [cloudflare/workerd#688]
TCP Socket API fail silently when operated from WebSocket context.

It is already [documented](https://developers.cloudflare.com/workers/runtime-apis/tcp-sockets/) that tcp cannot be created from non-request context, however, connected sockets are still expected to be available for read and write from WebSocket Context. In particular, when data are received on tcp socket, it should wake up the script for processing, like when receiving an message on WebSocket connection.

The following script don't work as intended.

It should on `WEBSOCKET ws://XXXXX/ws`:
1. connect to github.com:22 on request(for demo purpose only).
2. send TEST message to the socket.
3. accept websocket connection from client
4. when receiving websocket message from client, the message should be forwarded to socket.
5. (Not implemented in the script) When receive data on the socket, forward it to the client.

It, however, fails task 4-5. When receiving websocket message from client, the message is dropped and not send to the socket. 
Once in websocket context, connectedSocketReader also stop to receive data.(not shown in script below)

This functionality is required to proxy 2 way tcp connection to client in order to achieve database pubsub support, web based ssh(git, sftp), and general purpose transport layer proxy.

```js
import {connect} from 'cloudflare:sockets';


async function handleSession(websocket) {
    let destination = "github.com:22" // For demo only
    let connectedSocket = connect(destination)
    let connectedSocketWriter = connectedSocket.writable.getWriter()
    let connectedSocketReader = connectedSocket.readable.getReader()
    await connectedSocketWriter.write(new TextEncoder().encode("TEST"))
    websocket.accept()

    websocket.addEventListener("message", ({data}) => {
            connectedSocketWriter.write(data)
            console.log("written: " + data)
    })
}

const websocketHandler = async request => {
    const upgradeHeader = request.headers.get("Upgrade")
    if (upgradeHeader !== "websocket") {
        return new Response("Expected websocket", {status: 400})
    }

    const [client, server] = Object.values(new WebSocketPair())
    await handleSession(server)

    return new Response(null, {
        status: 101,
        webSocket: client
    })
}

async function handleRequest(request) {
    try {
        const url = new URL(request.url)
        switch (url.pathname) {
            case '/ws':
                return websocketHandler(request)
            default:
                return new Response("Not found", {status: 404})
        }
    } catch (err) {
        return new Response(err.toString())
    }
}

export default {
    async fetch(req, env, context) {
        return handleRequest(req)
    }
}
```

**Comment by kentonv** [comment]
There is nothing special about WebSocket event handlers that would make them unable to use sockets, so I think something else is wrong.

How do you know that data is being dropped? Is it because you don't see your `console.log` inside the message handler? Could that be because `connectedSocketWriter.write()` threw an exception, so the `console.log()` never ran?

When you send the string `TEST` to `github.com:22`, GitHub will respond by closing the connection, because this is not a valid way to start an SSH session. So it would not be surprising if your attempt to `write()` to it after that threw an exception.

**Comment by xiaokangwang** [comment]
Hi! Thanks for your reply. Sorry for not making myself more clear.

I know the data is dropped based on wireshark packet capture. Here is what I did:
1. start wireshark packet capture.
2. send websocket request to the worker script, and send two message to it.
3. find the connection to `github:22` made by the worker script with filter `tcp.port ==22 && tcp.flags.syn == 1` to narrow the search, and then follow the connection by right click on the connection, and click on  "Follow" -> "TCP Stream"
4. observe the packet flow.
![image](https://github.com/cloudflare/workerd/assets/1883569/b9122b3f-69d8-4230-a4ca-15ee76d82062)

On the console the follow text was outputted:
```
workerd/io/worker.c++:1544: info: console.log(); message() = ["written: dd"]
workerd/io/worker.c++:1544: info: console.log(); message() = ["written: dddd"]
```
We can see the write() returned without an exception, or any log to console even with `--verbose` flag on, and the data didn't show up on packet capture.

Github's SSH service didn't close connection because implementation of protocols always try to read certain length of data before beginning to process the data received. In this case `TEST` is not processed because it didn't reach that length.

(During my further testing, reading from socket is working, and writing to socket from websocket context isn't)

**Comment by kentonv** [comment]
I see. Can you try `await`ing the writes? Otherwise if they throw an exception asynchronously, it wouldn't be caught anywhere. I guess you should also wrap them in try/catch and console.log the error if you catch one.

FYI @dom96, something seems wrong with sockets here but I'd be surprised if it actually has to do with running in a WebSocket event handler, that shouldn't be an issue...

**Comment by xiaokangwang** [comment]
Thanks for your feedback. I have rewrite the program and determined the root cause of error being `socket.writable.getWriter()` does not accept `string` chunk, while the [document](https://developers.cloudflare.com/workers/runtime-apis/streams/writablestreamdefaultwriter) claim it supports `any`. **Sorry for sending invalid bug report**. I will try to improve the documents by sending a pull request.

Here is what happened after wrapping the socket with try/catch, the following error was reported:
```
workerd/io/worker.c++:1544: info: console.log(); message() = ["failed to write: TypeError: This TransformStream is being used as a byte stream, but received a string on its writable side. If you wish to write a string, you'll probably want to explicitly UTF-8-encode it with TextEncoder."]
```
WebSocket can receive/send both byte array or string messages. In this case, a string message was received. However, socket's `WritableStreamDefaultWriter` only accepts `Uint8Array` or its view. So it is necessary to type cast and process accordingly.  Plus, additional logic would be necessary to make sure the write to socket is in order, because the promise to write to the socket could be executed out of order, so the code below is not valid for actual usage.

The code I run:
```javascript
import {connect} from 'cloudflare:sockets';


async function handleSession(websocket) {
    let destination = "github.com:22" // For demo only
    let connectedSocket = connect(destination)
    let connectedSocketWriter = connectedSocket.writable.getWriter()
    let connectedSocketReader = connectedSocket.readable.getReader()
    await connectedSocketWriter.write(new TextEncoder().encode("TEST"))
    websocket.accept()

    websocket.addEventListener("message", ({data}) => {
        new Promise(async (resolve, reject) => { // For demo only
            try {
                await connectedSocketWriter.write(new TextEncoder().encode("TEST"))
                await connectedSocketWriter.write(data)
                console.log("written: " + data)
                resolve()
            } catch (err) {
                console.log("failed to write: " + err)
            }
        })
    })
}

const websocketHandler = async request => {
    const upgradeHeader = request.headers.get("Upgrade")
    if (upgradeHeader !== "websocket") {
        return new Response("Expected websocket", {status: 400})
    }

    const [client, server] = Object.values(new WebSocketPair())
    await handleSession(server)

    return new Response(null, {
        status: 101,
        webSocket: client
    })
}

async function handleRequest(request) {
    try {
        const url = new URL(request.url)
        switch (url.pathname) {
            case '/ws':
                return websocketHandler(request)
            default:
                return new Response("Not found", {status: 404})
        }
    } catch (err) {
        return new Response(err.toString())
    }
}

export default {
    async fetch(req, env, context) {
        return handleRequest(req)
    }
}
```

**Comment by kentonv** [comment]
Note that the WebSocket protocol itself distinguishes between text blobs and binary blobs. So which type you get depends entirely on which type the other end of the WebSocket wrote. It might make sense for your protocol to say that the client is required to always send bytes, not text.

> Plus, additional logic would be necessary to make sure the write to socket is in order, because the promise to write to the socket could be executed out of order, so the code below is not valid for actual usage.

Note that you do not have to wait for a promise from a previous write() to finish before starting the next write(). The writes will be performed in the order of the calls. The only problem is that if you don't wait for the previous write to finish, you may be buffering data in memory. If your WebSocket client sends data to the Worker faster than the TCP socket accepts it, the difference will fill up your memory until you hit the 128MB memory limit and the Worker is terminated. Unfortunately I'm not sure if there's any way to prevent this right now, as there is no API to apply backpressure on a WebSocket.

**Comment by xiaokangwang** [comment]
Yes! Thanks for your analysis in my use case!

The alternative of define sending binary protocol is if the input was in text format it will be encoded into binary before sending to remote. This would cause problem when it comes to different encoding, but may work for ascii text protocols.

Yes, in addition to lack of built-in back pressure(won't be an issue unless is uploading file). It seems each copy consumes CPU time(about 100-200 MB of download for 10 ms CPU time), so the user need to account for this when developing applications that couldn't easily resume connection.
