### ISSUE TITLE
🐛 Bug Report — Runtime APIs: : D1 Does Not Allow `ALTER TABLE RENAME COLUMN` in Queries

### ISSUE THREAD

**Issue by itsmatteomanf** [cloudflare/workerd#729]
The Experimental Backend doesn't allow using `ALTER TABLE RENAME COLUMN` which should be supported in latest SQLite.

**Comment by elithrar** [comment]
Per: https://discord.com/channels/595317990191398933/992060581832032316/1109973517182701598

> Hey I'm having some issues with my migrations. For some reason D1 errors out when I try to rename tables. Does anyone have a workaround for this?
>
> not authorized to use function: `sqlite_rename_table`
