### ISSUE TITLE
🐛 BUG: Error: Origin SSL Handshake Error (525) when making requests to deepl API

### ISSUE THREAD

**Issue by Zombobot1** [cloudflare/workerd#776]
### Which Cloudflare product(s) does this pertain to?

Workers/Other

### What version of `Wrangler` are you using?

3.1.0

### What operating system are you using?

Mac

### Describe the Bug

It is impossible to query deepl API from workers.

The bug was first mentioned in August 2021 on the [forum](https://community.cloudflare.com/t/error-origin-ssl-handshake-error-525/294302). It was stated that "this is typically caused by a configuration issue in the origin web server". I opened a corresponding [issue](https://github.com/DeepLcom/deepl-node/issues/14#issuecomment-1584983165) in their repo and they concluded that "the problem lies with cloudflare workers". Can you take a look at this problem? Other services might be unreachable as well.

Deepl is a very popular product and it is sad that it can be used with workers.

Code to reproduce

```ts
const deepLUrl = 'https://api-free.deepl.com/v2/translate'
const text = 'I like my cat'
const to = 'de'
const from = 'en'

const resp = await fetch(deepLUrl, {
  method: 'POST',
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
    Authorization: `DeepL-Auth-Key ${env.DEEPL}`,
  },
  body: `text=${encodeURIComponent(text)}&target_lang=${to.toUpperCase()}&source_lang=${from.toUpperCase()}`,
})
if (!resp.ok) throw new Error(`DeepL error (${resp.status}) ` + resp.statusText) // throws in workers
const response = await resp.json()
response.translations[0].text // works in node
```

**Comment by kentonv** [comment]
@Zombobot1 Can you please make sure your zone's SSL mode is "Full" and not "Flexible"? Let me know if that solves the problem.

**Comment by Zombobot1** [comment]
I [asked](https://github.com/DeepLcom/deepl-node/issues/14#issuecomment-1600433721) the deepl team about this and they cannot find this setting. Could you please explain this in more detail?

**Comment by kentonv** [comment]
This is not a problem with deepl, it's an issue with your Cloudflare account where you're hosting your Worker. I believe you may have your SSL mode set to "Flexible" and you're running into a bug with that.

On https://dash.cloudflare.com, log in and open your zone (domain), and then look for this in the sidebar:

![Screenshot from 2023-06-24 10-20-28](https://github.com/cloudflare/workerd/assets/4001805/fa066671-f5a8-417d-8ffd-76a080a589da)

On that page, the setting looks like this:

![Screenshot from 2023-06-24 10-20-04](https://github.com/cloudflare/workerd/assets/4001805/1c4e4a79-7dd7-4ab9-84cd-1affb45f411c)

Please make sure it's set to one of Full, Full (strict), or Strict.

Let me know if that helps.

**Comment by Omarov3000** [comment]
Probably I'm missing something. I have my worker on `ub-ai.unni.workers.dev`. Why should I change the encryption mode on my website?

---

I added a custom domain to my worker:
![image](https://github.com/cloudflare/workerd/assets/64260942/85933ed8-e841-44d0-92f9-16db04ad1e1b)

For this domain (theunni.com) I selected full ssl mode
![image](https://github.com/cloudflare/workerd/assets/64260942/d42c75a1-f211-4c73-8948-d7aecbbbe616)

I still get 525 error when I'm requesting deepl from my worker on `api.theunni.com`

Have I missed something?

**Comment by Zombobot1** [comment]
Probably I'm missing something. I have my worker on `ub-ai.unni.workers.dev`. Why should I change the encryption mode on my website?

---

I added a custom domain to my worker:
![image](https://github.com/cloudflare/workerd/assets/48030070/f5dfaa00-65a5-4859-b5cd-2341b868357e)


For this domain (theunni.com) I selected full ssl mode
![image](https://github.com/cloudflare/workerd/assets/48030070/6c215c3a-2142-4a3f-8c75-7dff61b514b6)

I still get 525 error when I'm requesting deepl from my worker on `api.theunni.com`

Have I missed something?

**Comment by kentonv** [comment]
Oh, right... if this is on workers.dev, then SSL mode shouldn't be an issue. Darn, I guess that's not it then.

Somehow it seems like deepl's SSL server configuration and the way Cloudflare behaves as an SSL client are not compatible with each other. I'm afraid this is outside my area of knowledge since SSL termination occurs outside of the Workers system, but I'll see if I can ping someone...

**Comment by tomardern** [comment]
hey @kentonv - we're getting the same error when trying to connect to DeepL API.

We're running on cloudflare workers - on the workers.dev domain (and therefore do not have a zone setup).

Any ideas?

**Comment by kentonv** [comment]
@irvinebroque Any updates on this?

**Comment by Omarov3000** [comment]
We had to move our project to AWS because of this problem 😞.

**Comment by irvinebroque** [comment]
Hey @Omarov3000 and @tomardern — digging into this internally, thanks for flagging.

**Comment by tomardern** [comment]
Amazing, thank you @irvinebroque :) Very much appreciated.

**Comment by tomardern** [comment]
hi @irvinebroque - hope you had a good weekend. It's been three weeks since the last update. Has any further progress been made?

**Comment by gas9000** [comment]
We also had to move back to AWS at my company because of this issue 🙁.

**Comment by tomardern** [comment]
Sorry to be "_that guy_ - but is there any update here @irvinebroque?

**Comment by irvinebroque** [comment]
Relevant teams have identified the issue, and expect to address towards the end of this year (2023).

Since this issue is not about the open-source Workers Runtime, closing this issue. If you have further questions, please [contact Cloudflare support](https://dash.cloudflare.com/?to=/:account/support).

**Comment by tomardern** [comment]
👍 Thanks for the update @irvinebroque.

Based on the 525 handshake error, we've moved away from DeepL and instead found that the new Cloudflare Workers AI Translation model is good enough for our needs: https://developers.cloudflare.com/workers-ai/models/translation/ It's not perfect, doesn't allow "excluded terms" or anything fancy, but it may be a stop-gap until this issue is fixed.

**Comment by CNSeniorious000** [comment]
> Based on the 525 handshake error, we've moved away from DeepL and instead found that the new Cloudflare Workers AI Translation model is good enough for our needs: https://developers.cloudflare.com/workers-ai/models/translation/ It's not perfect, doesn't allow "excluded terms" or anything fancy, but it may be a good stop-gap until this issue is fixed.

I encountered exactly the same problem as yours. Cloudflare-hosted AI translators is not perfect for me so I migrated to DeepL. But when call DeepL's API on Vercel Edge Runtime, I meet the same strange 525 error.

How I solve this is simply to start a proxy service for it. It is simple to start a proxy service on Netlify, just using a `netlify.toml` like this:

```toml
[[redirects]]
  from = "/*"
  to = "https://api-free.deepl.com/:splat"
  status = 200
```

This works well for me.

**Comment by kiwiflydream** [comment]
> Relevant teams have identified the issue, and expect to address towards the end of this year (2023).
> 
> Since this issue is not about the open-source Workers Runtime, closing this issue. If you have further questions, please [contact Cloudflare support](https://dash.cloudflare.com/?to=/:account/support).

This issue still exists as of the current date (2024-01-05)

**Comment by tbrockman** [comment]
And adding another comment as someone who encountered this, was looking to use Cloudflare Workers, but will now be investigating alternatives.

**Comment by Boscop** [comment]
I just ran into this issue as well, when calling DeepL API from my worker. 
Can you please reopen this issue?

I'm wondering why this is apparently so hard to fix..
Did anyone find a workaround? :)

**Comment by Boscop** [comment]
@tomardern Hey, do you know where I can find the list of languages supported by workers-ai?
[This](https://developers.cloudflare.com/workers-ai/models/translation/) page just says "languages: english, chinese, french, spanish, arabic, russian, german, japanese, portuguese, hindi" but it links to [this](https://github.com/facebookresearch/fairseq/tree/main/examples/m2m_100) page which says "In this work, we create a true Many-to-Many multilingual translation model that can translate directly between any pair of 100 languages." but it doesn't say **which languages** it supports!
So I'm wondering, what's the full list of supported languages of workers-ai (`@cf/meta/m2m100-1.2b`)?

**Comment by lolandkidtress** [comment]
This issue still exists 2024-07-19

**Comment by J-Giggles** [comment]
This issue still exists 2024-08-02. Looks like I will be deploying the API on another service

**Comment by J-Giggles** [comment]
For anyone who needs help understanding the Netlify workaround. This works:)

Steps to Set Up a Proxy Service on Netlify

1. Create a Project Directory in your current project or else ware: 
```
mkdir my-netlify-proxy
cd my-netlify-proxy
```

2. Create a netlify.toml file

3. Configure Netlify with netlify.toml: 
```
[[redirects]]
  from = "/*"
  to = "https://api-free.deepl.com/:splat"
  status = 200
```

(Optional: If you don't have Netlify installed
`npm install netlify-cli --save-dev`

4. Deploy to Netlify: Run the following command in the terminal from the project directory to deploy it to Netlify.
`netlify deploy -d . -p`

**Comment by sayhicoelho** [comment]
Facing the same issue here 😥

**Comment by EvilIrving** [comment]
This issue still exists 2024-10-10

**Comment by MurmeltierS** [comment]
still a issue (wtf)

**Comment by OultimoCoder** [comment]
@irvinebroque Any update on this issue?

**Comment by super-morris** [comment]
@cloudflare come on.... 1 1/2 years?

**Comment by stan-devproject** [comment]
Same issue :( Big thanks to @J-Giggles and @CNSeniorious000 for netlify proxy hack, worked for me. But Cloudflare definitely should fix that!

**Comment by OultimoCoder** [comment]
yeah but fuck relying on an external proxy, cmon Cloudflare

**Comment by alexanderniebuhr** [comment]
@irvinebroque Hope you are doing well? I'm currently working with a client, migrating their whole backend to workers, even using the new workflows.. However this issue starts to block the migration, they do have an enterprise plan.. Can we get this issue fixed internally at CF, please? Or can you share any workarounds using CF platform, e.g. page rules, etc.?

**Comment by LeonHeidelbach** [comment]
@irvinebroque This issue has now been unresolved for over 1 year and 8 months and when searching online I could even find posts referencing this problem from back in 2021. I can really not believe that this is not fixed yet. Are there any updates on this and can we please reopen this issue as it has clearly not been fixed? Maybe 2025 is going to be THE YEAR...

**Comment by isaacrowntree** [comment]
Many thanks @J-Giggles this helped me significantly!

C'mon Cloudflare, stop playing around with AI and fix my DeepL Woes 😛

**Comment by muratcankaracabey** [comment]
Still an issue :D will switch to another serverless provider probably...

**Comment by JanEbbing** [comment]
I believe this should be fixed now, but I dont have access to a cloudflare worker to test. Can someone try this out please (using the DeepL API from a CF worker)?

**Comment by super-morris** [comment]
@JanEbbing I can confirm, it finally works.👯

**Comment by elsbrock** [comment]
Seeing the same with api.letsencrypt.org:

Minimal repo:

```
export default {
  async fetch() {
    return fetch("https://acme-v02.api.letsencrypt.org/directory");
  },
};
```

returns error code: 525

Is there any potential workaround without relaying?
