### ISSUE TITLE
🐛 Experimental backend too restrictive on compount SELECT statement limits

### ISSUE THREAD

**Issue by betimshahini** [cloudflare/workerd#795]
The experimental D1 backend configuration seems to have set limits around the compound SELECT statements that align with the SQLite high-security guidelines, but conflict with fairly simple use cases of having to combine results of multiple select statements using UNION ALL. For my use case, that works well in the non-experimental backend, my query unions 6 statements. I'd imagine a "safe" limit would be 10 if not higher, for broader applicability.

This restriction isn't applicable in the regular (non-experimental) backend. 

Expected behaviour:
`select 1 union all select 1 union all select 1 union all select 1` should work equally well as `select 1 union all select 1 union all select 1` 

Actual behaviour:
SQLite error: `too many terms in compound SELECT` when the number of SELECT statements in a union exceeds 3.

Context for the limitation (provided by @rozenmd in Discord): https://github.com/cloudflare/workerd/blob/cfe19fdd962c2898dcb4a4bd0c4e1b2a60949f74/src/workerd/util/sqlite.c%2B%2B#L645

**Comment by elithrar** [comment]
@betimshahini - can you share a real world query that isn’t working?

Large UNION ALLs both tend to have poor performance and this doesn’t help us understand how typical this usage is.
