### ISSUE TITLE
🐛 Bug Report — Runtime APIs - Making a new request to a bound service causes a "The script will never generate a response." error

### ISSUE THREAD

**Issue by asimpletune** [cloudflare/workerd#825]
I'm seeing this issue only when a new request is constructed, not when a request is constructed from another request. 

For example, the following code will succeed:

```typescript
// This works
async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
  env.v1_API.fetch(new Request("https://foo.com/v1/toml/parse", request))
```

However, in a situation where I can't copy the underlying request, say for example in an email handler, I get the dreaded "The script will never generate a response." error, for example:

```typescript
// This seems to be impossible
async email(initialEmail: ForwardableEmailMessage, env: Env, ctx: ExecutionContext) {
  return env.v1_API.fetch(new Request("https://foo.com/v1/toml/parse"))
```

Unfortunately, I can easily do the second example if the request is not done through service bindings, but then what's the point of service bindings?

**Comment by kentonv** [comment]
Can you please provide a complete self-contained test case that demonstrates this problem?

**Comment by asimpletune** [comment]
Hey Kenton, thanks for the follow up. 

## Steps to reproduce:

```sh
# step 1: setup service b
wrangler generate service_b https://github.com/asimpletune/cf_issue-825_service-b && npm install && wrangler publish

# step 2: setup service a
wrangler generate service_a https://github.com/asimpletune/cf_issue-825_service-a && npm install && wrangler deploy

# step 3. call service a at /parse_mail_[1...4], and pass in `hello_world.eml` file as argument:
curl --data-binary @hello_world.eml <SVC_A_WORKER_DEV>/parse_mail_1
curl --data-binary @hello_world.eml <SVC_A_WORKER_DEV>/parse_mail_2
curl --data-binary @hello_world.eml <SVC_A_WORKER_DEV>/parse_mail_3
curl --data-binary @hello_world.eml <SVC_A_WORKER_DEV>/parse_mail_4
```

Also, if you set up an email trigger you can test the email handler in service a as well. 

## Expect vs Actual
 
I expect `/parse_mail_1` - `/parse_mail_4`  to work, but what I actually see is that requests to `/parse_mail_1` and `/parse_mail_2` fail with "The script will never generate a response.", and request to `/parse_mail_3` and `/parse_mail_4` succeed. 

Sending an email triggers the same failure, which is not what is expected. 

## More information about Services

Service A is just a simple typescript cloudflare worker that switches on the request path and calls Service B, which is bound to A. 

```typescript
// e.g. `curl --data-binary @hello_world.eml https://service_a.spence.workers.dev/parse_mail_1`
export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		let url = new URL(request.url)
		switch (url.pathname) {
			// Fails
			case "/parse_mail_1": return env.ParseMail.fetch("https://foo.com", { method: "POST", body: request.body })
			// Fails
			case "/parse_mail_2": return env.ParseMail.fetch(new Request("https://foo.com", { method: "POST", body: request.body }))
			// Succeeds
			case "/parse_mail_3": return env.ParseMail.fetch("https://foo.com", request)
			// Succeeds
			case "/parse_mail_4": return env.ParseMail.fetch(new Request("https://foo.com", request))
			default: return new Response()
		}
	},
	async email(email: ForwardableEmailMessage, env: Env, ctx: ExecutionContext) {

		return env.ParseMail.fetch("https://foo.com", { method: "POST", body: email.raw })
			.then(response => response.text())
			.then(text => { console.log(text); return new Response() })
	}
};
```

Service B is a rust worker that uses a mail-parser library and serve to parse the text and return the response as JSON. 

```rust
use worker::*;
mod utils;
use mail_parser::*;
use serde_json::json;

fn log_request(req: &Request) {
    console_log!(
        "{} - [{}], located at: {:?}, within: {}",
        Date::now().to_string(),
        req.path(),
        req.cf().coordinates().unwrap_or_default(),
        req.cf().region().unwrap_or("unknown region".into())
    );
}

#[event(fetch)]
async fn main(mut req: Request, _: Env, _: Context) -> Result<Response> {
    log_request(&req);

    // Optionally, get more helpful error messages written to the console in the case of a panic.
    utils::set_panic_hook();

    match req.method() {
        Method::Post => match req.bytes().await {
            Ok(email_bytes) => match Message::parse(&email_bytes) {
                Some(message) => return Response::from_json(&json!(message)),
                None => return Response::error("Bad Request", 400),
            },
            Err(_) => return Response::error("Bad Request", 400),
        },
        Method::Get => return Response::ok("Hello, world!"),
        _ => return Response::error("Method Not Allowed", 405),
    }
}

```

**Comment by asimpletune** [comment]
Basically

```typescript
// this fails BUT
env.ParseMail.fetch("https://foo.com", { method: "POST", body: request.body })` 

 // this succeeds
env.ParseMail.fetch("https://foo.com", request)
```

I took a look at the `workerd` code after filing this bug and it looks like there are two, nested checks made [before the error is thrown](https://github.com/cloudflare/workerd/blob/4fb4dbd88d30ff293267680d85a31ddef94fd9b6/src/workerd/io/io-context.c%2B%2B#L1260). The inner check:

```cpp
if (limitEnforcer->getLimitsExceeded() == nullptr)
``` 

Seems to  return `nullptr` [everywhere](https://github.com/search?q=repo%3Acloudflare/workerd%20getLimitsExceeded&type=code). And the outer check

```cpp
if (abortFulfiller->isWaiting()) {
```

Depends on whether an abort request has been queued I think. I was looking at places where abort requests were getting queued, and it seemed like the key was to searching for where `paf` is used, but I didn't look very deeply and it seems kind of complicated.

Please don't hesitate to let me know if you have any ideas where I can search more closely, and maybe I can help ease some of the load.

**Comment by kentonv** [comment]
@jasnell Could this be a streams bug? For some reason propagating `request.body` explicitly causes a missing pending event when sending a subrequest?

**Comment by asimpletune** [comment]
I know the root cause of the issue. `service_b` is a rust worker, and making the request mutable in the fetch handler that triggers the issue. 

```rust
// This succeeds
#[event(fetch)]
async fn main(req: Request, _: Env, _: Context) -> Result<Response> {
    Response::ok("OK")
}
```

```rust
// This fails
#[event(fetch)]
async fn main(mut req: Request, _: Env, _: Context) -> Result<Response> {
    Response::ok("OK")
}
```

**Comment by asimpletune** [comment]
Since this is an issue with `worker-rs` I'll go ahead and close this and submit a fix there. Thanks for everyone's patience.
