### ISSUE TITLE
[workers] Document properties of WebSocket instance returned by WebSocketPair

### ISSUE THREAD

**Issue by 0x62** [cloudflare/workerd#905]
### Expected Behavior
`new WebSocketPair()` returns (relatively) standard implementations of the `WebSocket` class

### Actual Behavior
`ws.readyState` is undefined on server half

### Section that requires update
https://developers.cloudflare.com/workers/learning/using-websockets

### Additional information
Document any non-standard behaviour and properties of WebSocket instance

**Comment by kentonv** [comment]
cc @MellowYarker who I think has context on this code

**Comment by MellowYarker** [comment]
This was fixed a long time ago.

**Comment by irvinebroque** [comment]
Hmmm when I naively create a new `WebSocketPair`, and try to access `readyState` on the server half, it appears undefined to me.

**Comment by MellowYarker** [comment]
Mind sending a repro? I'm getting a value of 1 (open) in tests and in production (after `new WebSocketPair()`, before `ws.accept()`)

**Comment by irvinebroque** [comment]
Nvm you are right :)
