### ISSUE TITLE
`new Response(readableStream).arrayBuffer()` stopped working for streams longer than ~`247` bytes at ~`2023-08-03 20:44:17 +0000 UTC`

### ISSUE THREAD

**Issue by CetinSert** [cloudflare/workerd#970]
From https://discord.com/channels/595317990191398933/1012440514135593083/1136901294196535387

---

(

This turned out to be a regression in `workerd` which will affect non-WfP workers too!
See this comment for the root cause and our workaround: https://github.com/cloudflare/workerd/issues/970#issuecomment-1665373143

)

We see a complete failure of certain routes that use WfP without any code changes on our end.
First health check failure: `2023-08-03 20:44:17 +0000 UTC` 
Last health check failure: `2023-08-04 05:59:04 +0000 UTC` (Status `500`)
The logs show:
```json
  "exceptions": [
    {
      "name": "Error",
      "message": "The script will never generate a response.",
      "timestamp": 1691128921644
    }
  ]
```
some failing routes:
https://rtedge.net/
https://elefunc.com/
(These routes now work after we applied the workaround in ⁠https://github.com/cloudflare/workerd/issues/970#issuecomment-1665373143) 

---

```js
const st = { // comp.rt.ht

  fo: ['gzip','deflate'][0],

  id: x => x,

  co: (s, f = st.fo) => { if (s === null || s === undefined) return s;
    const c = new CompressionStream(f);
    const w = c.writable.getWriter();
    /**/  w.write(new TextEncoder().encode(s));
    /**/  w.close();
    return new Response(c.readable).arrayBuffer();
  },

  de: (B, f = st.fo) => { if (B === null || B === undefined) return B;
    const d = new DecompressionStream(f);
    const w = d.writable.getWriter();
    /**/  w.write(B);
    /**/  w.close();
    return new Response(d.readable).arrayBuffer().then(B => new TextDecoder().decode(B)).catch(_ => new TextDecoder().decode(B));
  }

};
```

we have found the call triggering the regression after your update, it is in our exported fetch when we call:
`await st.de(v)` where `v` is an `ArrayBuffer` instance!
This used to work before `2023-08-03 20:44:17 +0000 UTC` and now it does not. 

---

If `v.byteLength` is `243` or less, decompression succeeds.
If `v.byteLength` is `247` or more, we now get `The script will never generate a response.`.
Decompression never took more than `50ms` in any of our deployed routes. I believe whatever causes the error triggers falsely now.

**Comment by CetinSert** [comment]
**Here is what regressed!**
This used to always work in `st.de`:
```js
new Response(d.readable).arrayBuffer()
```
and has stopped working at `2023-08-03 20:44:17 +0000 UTC`
with `The script will never generate a response.` errors, 
for `ReadableStreams` longer than ~`247` bytes. 
Having GPT4 switch our code to use manual concatenation resolved the issue:
```js
ReadableStream.prototype.arrayBuffer = async function() { return st.ab(this); };

const st = { // comp.rt.ht

  fo: ['gzip','deflate'][0],

  id: x => x,

  ab: async r => {
    const  R  = r.getReader();
    const  C  = []; while (true) { const { done, value } = await R.read(); if (done) break; C.push(value); }
    const  AB = new Uint8Array(C.reduce((a, b) => a + b.length, 0)); let p = 0; for (let c of C) { AB.set(c, p); p += c.length; }
    return AB;
  },

  co: (s, f = st.fo) => { if (s === null || s === undefined) return s;
    const c = new CompressionStream(f);
    const w = c.writable.getWriter();
    /**/  w.write(new TextEncoder().encode(s));
    /**/  w.close();
    return c.readable.arrayBuffer();
  },

  de: (B, f = st.fo) => { if (B === null || B === undefined) return B;
    const d = new DecompressionStream(f);
    const w = d.writable.getWriter();
    w.write(B);
    w.close();
    return d.readable.arrayBuffer().then(B => new TextDecoder().decode(B)).catch(_ => new TextDecoder().decode(B));
  }

};
```

**Comment by mikea** [comment]
@CetinSert here's a simple test using response of readable stream:

```
export const arrayBufferOfReadable = {
  async test() {
    const rs = new ReadableStream({
      type: 'bytes',
      start(controller) {
        const enc = new TextEncoder();
        controller.enqueue(enc.encode('0123456789'.repeat(1000)));
        controller.close();
      }
    });

    const read = await new Response(rs).arrayBuffer();
    assert.equal(10_000, read.byteLength);
  }
}
```

seems to pass if you add it to `streams-test.js`. Is there a critical step missing here?

**Comment by mikea** [comment]
I think I have a reproduce in #974 and revert is up in #973

**Comment by CetinSert** [comment]
@mikea – has this been reverted at all `workerd` deployments globally?

**Comment by irvinebroque** [comment]
@CetinSert — we are in the process of reverting this change in production and will post here once that is complete.

**Comment by mikea** [comment]
@CetinSert the revert should be complete by now

**Comment by CetinSert** [comment]
@mikea – thank you for the prompt response!
Confirming with global Health Checks over the next 5 hours.
I will update and close the issue here by morning (New York).

**Comment by CetinSert** [comment]
Sorry for the summer-slow response!
This is just working flawlessly again.
